"""removing tenant from RiskModelBase

Revision ID: 0183b6461709
Revises: ae4ef53e609b
Create Date: 2022-03-09 12:23:36.732960

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "0183b6461709"
down_revision = "ae4ef53e609b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("rm_average_contractor_safety_score", "tenant")
    op.drop_column("rm_average_supervisor_engagement_factor", "tenant")
    op.drop_column("rm_contractor_project_execution", "tenant")
    op.drop_column("rm_contractor_safety_history", "tenant")
    op.drop_column("rm_contractor_safety_rating", "tenant")
    op.drop_column("rm_contractor_safety_score", "tenant")
    op.drop_column("rm_gbl_contractor_project_history_bsl", "tenant")
    op.drop_column("rm_gbl_contractor_project_history_bsl_stddev", "tenant")
    op.drop_column("rm_manually_added_site_conditions", "tenant")
    op.drop_column("rm_project_location_safety_climate_multiplier", "tenant")
    op.drop_column("rm_project_location_total_task_risk_score", "tenant")
    op.drop_column("rm_project_site_conditions_multiplier", "tenant")
    op.drop_column("rm_project_total_task_risk_score", "tenant")
    op.drop_column("rm_stddev_contractor_safety_score", "tenant")
    op.drop_column("rm_stddev_supervisor_engagement_factor", "tenant")
    op.drop_column("rm_supervisor_engagement_factor", "tenant")
    op.drop_column("rm_surface_project_project_location_risk_scores", "tenant")
    op.drop_column("rm_surface_total_task_task_specific_risk_ranking", "tenant")
    op.drop_column("rm_task_specific_risk_score", "tenant")
    op.drop_column("rm_task_specific_safety_climate_multiplier", "tenant")
    op.drop_column("rm_task_specific_site_conditions_multiplier", "tenant")
    op.drop_column("rm_total_project_location_risk_score", "tenant")
    op.drop_column("rm_total_project_risk_score", "tenant")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "rm_total_project_risk_score",
        sa.Column("tenant", postgresql.UUID(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "rm_total_project_location_risk_score",
        sa.Column("tenant", postgresql.UUID(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "rm_task_specific_site_conditions_multiplier",
        sa.Column("tenant", postgresql.UUID(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "rm_task_specific_safety_climate_multiplier",
        sa.Column("tenant", postgresql.UUID(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "rm_task_specific_risk_score",
        sa.Column("tenant", postgresql.UUID(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "rm_surface_total_task_task_specific_risk_ranking",
        sa.Column("tenant", postgresql.UUID(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "rm_surface_project_project_location_risk_scores",
        sa.Column("tenant", postgresql.UUID(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "rm_supervisor_engagement_factor",
        sa.Column("tenant", postgresql.UUID(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "rm_stddev_supervisor_engagement_factor",
        sa.Column("tenant", postgresql.UUID(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "rm_stddev_contractor_safety_score",
        sa.Column("tenant", postgresql.UUID(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "rm_project_total_task_risk_score",
        sa.Column("tenant", postgresql.UUID(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "rm_project_site_conditions_multiplier",
        sa.Column("tenant", postgresql.UUID(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "rm_project_location_total_task_risk_score",
        sa.Column("tenant", postgresql.UUID(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "rm_project_location_safety_climate_multiplier",
        sa.Column("tenant", postgresql.UUID(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "rm_manually_added_site_conditions",
        sa.Column("tenant", postgresql.UUID(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "rm_gbl_contractor_project_history_bsl_stddev",
        sa.Column("tenant", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "rm_gbl_contractor_project_history_bsl",
        sa.Column("tenant", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "rm_contractor_safety_score",
        sa.Column("tenant", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "rm_contractor_safety_rating",
        sa.Column("tenant", postgresql.UUID(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "rm_contractor_safety_history",
        sa.Column("tenant", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "rm_contractor_project_execution",
        sa.Column("tenant", postgresql.UUID(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "rm_average_supervisor_engagement_factor",
        sa.Column("tenant", postgresql.UUID(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "rm_average_contractor_safety_score",
        sa.Column("tenant", postgresql.UUID(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
