"""Added new metrics Average & StdDev for Contractor Safety Score & Supervisor Safety Score

Revision ID: 0c7bd349a563
Revises: f50c0f494131
Create Date: 2022-02-14 15:23:42.944377

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "0c7bd349a563"
down_revision = "f50c0f494131"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rm_average_contractor_safety_score",
        sa.Column("calculated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("tenant", sqlmodel.sql.sqltypes.GUID(), nullable=True),
        sa.Column("tenant_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.PrimaryKeyConstraint("calculated_at"),
    )
    op.create_table(
        "rm_average_supervisor_engagement_factor",
        sa.Column("calculated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("tenant", sqlmodel.sql.sqltypes.GUID(), nullable=True),
        sa.Column("tenant_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.PrimaryKeyConstraint("calculated_at"),
    )
    op.create_table(
        "rm_stddev_contractor_safety_score",
        sa.Column("calculated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("tenant", sqlmodel.sql.sqltypes.GUID(), nullable=True),
        sa.Column("tenant_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.PrimaryKeyConstraint("calculated_at"),
    )
    op.create_table(
        "rm_stddev_supervisor_engagement_factor",
        sa.Column("calculated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("tenant", sqlmodel.sql.sqltypes.GUID(), nullable=True),
        sa.Column("tenant_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.PrimaryKeyConstraint("calculated_at"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("rm_stddev_supervisor_engagement_factor")
    op.drop_table("rm_stddev_contractor_safety_score")
    op.drop_table("rm_average_supervisor_engagement_factor")
    op.drop_table("rm_average_contractor_safety_score")
    # ### end Alembic commands ###
