"""Adding params as a field in RiskModelBase

Revision ID: 16bf7ed30aae
Revises: d33a76a64654
Create Date: 2022-03-15 16:08:50.269858

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "16bf7ed30aae"
down_revision = "31743d9f00af"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "rm_average_contractor_safety_score",
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "rm_average_supervisor_engagement_factor",
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "rm_contractor_project_execution",
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "rm_contractor_safety_history",
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "rm_contractor_safety_rating",
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "rm_contractor_safety_score",
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "rm_gbl_contractor_project_history_bsl",
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "rm_gbl_contractor_project_history_bsl_stddev",
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "rm_manually_added_site_conditions",
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "rm_project_location_safety_climate_multiplier",
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "rm_project_location_total_task_risk_score",
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "rm_project_site_conditions_multiplier",
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "rm_project_total_task_risk_score",
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "rm_stddev_contractor_safety_score",
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "rm_stddev_supervisor_engagement_factor",
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "rm_supervisor_engagement_factor",
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "rm_surface_project_project_location_risk_scores",
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "rm_surface_total_task_task_specific_risk_ranking",
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "rm_task_specific_risk_score",
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "rm_task_specific_safety_climate_multiplier",
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "rm_task_specific_site_conditions_multiplier",
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "rm_total_project_location_risk_score",
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "rm_total_project_risk_score",
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("rm_total_project_risk_score", "params")
    op.drop_column("rm_total_project_location_risk_score", "params")
    op.drop_column("rm_task_specific_site_conditions_multiplier", "params")
    op.drop_column("rm_task_specific_safety_climate_multiplier", "params")
    op.drop_column("rm_task_specific_risk_score", "params")
    op.drop_column("rm_surface_total_task_task_specific_risk_ranking", "params")
    op.drop_column("rm_surface_project_project_location_risk_scores", "params")
    op.drop_column("rm_supervisor_engagement_factor", "params")
    op.drop_column("rm_stddev_supervisor_engagement_factor", "params")
    op.drop_column("rm_stddev_contractor_safety_score", "params")
    op.drop_column("rm_project_total_task_risk_score", "params")
    op.drop_column("rm_project_site_conditions_multiplier", "params")
    op.drop_column("rm_project_location_total_task_risk_score", "params")
    op.drop_column("rm_project_location_safety_climate_multiplier", "params")
    op.drop_column("rm_manually_added_site_conditions", "params")
    op.drop_column("rm_gbl_contractor_project_history_bsl_stddev", "params")
    op.drop_column("rm_gbl_contractor_project_history_bsl", "params")
    op.drop_column("rm_contractor_safety_score", "params")
    op.drop_column("rm_contractor_safety_rating", "params")
    op.drop_column("rm_contractor_safety_history", "params")
    op.drop_column("rm_contractor_project_execution", "params")
    op.drop_column("rm_average_supervisor_engagement_factor", "params")
    op.drop_column("rm_average_contractor_safety_score", "params")
    # ### end Alembic commands ###
