"""add handle code to site conditions

Revision ID: 280253ca8cbd
Revises: 9886bc17840e
Create Date: 2022-02-15 17:33:33.747143

"""
import os

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "280253ca8cbd"
down_revision = "9886bc17840e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "library_site_conditions",
        sa.Column("handle_code", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.create_unique_constraint(
        "library_site_conditions_handle_code_unique",
        "library_site_conditions",
        ["handle_code"],
    )
    # ### end Alembic commands ###
    fixture_path = os.fsencode(
        "migrations/fixtures/postgres_public_library_site_conditions_handle_code.sql"
    )
    with open(fixture_path) as file:
        escaped_sql = sa.text(file.read())
    op.execute(escaped_sql)


def downgrade():
    op.execute(
        "DELETE FROM public.library_site_conditions WHERE handle_code = 'road_closed'"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "library_site_conditions_handle_code_unique",
        "library_site_conditions",
        type_="unique",
    )
    op.drop_column("library_site_conditions", "handle_code")
    # ### end Alembic commands ###
