"""create rm_contractor_safety_history table

Revision ID: 2a7f9b19772e
Revises: c58c98ba4140
Create Date: 2022-01-18 17:18:50.139137

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2a7f9b19772e"
down_revision = "c58c98ba4140"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rm_contractor_safety_history",
        sa.Column("calculated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("calculated_at"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("rm_contractor_safety_history")
    # ### end Alembic commands ###
