"""add details to calculated site conditions

Revision ID: 2acf99e204f6
Revises: dc0801eb6a09
Create Date: 2022-03-22 10:58:09.005582

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "2acf99e204f6"
down_revision = "dc0801eb6a09"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "calculated_project_location_site_condition",
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "calculated_project_location_site_condition",
        sa.Column("multiplier", sa.Float(), nullable=False, server_default="0.0"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("calculated_project_location_site_condition", "multiplier")
    op.drop_column("calculated_project_location_site_condition", "details")
    # ### end Alembic commands ###
