"""creating initial 'global' risk model parameter table

Revision ID: 36edbbeadb1d
Revises: 2a7f9b19772e
Create Date: 2022-01-18 17:59:11.436612

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "36edbbeadb1d"
down_revision = "2a7f9b19772e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rm_calc_parameters",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("tenant", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("value", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    op.execute(
        """INSERT INTO rm_calc_parameters (name, value) VALUES
            ('contractor_safety_history_near_miss', '0.001'),
            ('contractor_safety_history_first_aid', '0.007'),
            ('contractor_safety_history_recordable', '0.033'),
            ('contractor_safety_history_restricted', '0.033'),
            ('contractor_safety_history_lost_time', '0.067'),
            ('contractor_safety_history_p_sif', '0.10'),
            ('contractor_safety_history_sif', '0.10');"""
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("rm_calc_parameters")
    # ### end Alembic commands ###
