"""Creating contractor safety rating model and adding contractor_id to contractor safety score

Revision ID: 45b98093cb11
Revises: 3cf5963680b3
Create Date: 2022-01-27 15:11:45.323940

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "45b98093cb11"
down_revision = "3cf5963680b3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rm_contractor_safety_rating",
        sa.Column("calculated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("tenant", sqlmodel.sql.sqltypes.GUID(), nullable=True),
        sa.Column("contractor_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.PrimaryKeyConstraint("calculated_at", "contractor_id"),
    )
    op.add_column(
        "rm_contractor_safety_score",
        sa.Column("contractor_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("rm_contractor_safety_score", "contractor_id")
    op.drop_table("rm_contractor_safety_rating")
    # ### end Alembic commands ###
