"""Create StochasticTotalLocationRiskScoreModel Table

Revision ID: 4b9d3ddd0cb2
Revises: b6f903208edd
Create Date: 2022-10-11 11:19:07.298467

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "4b9d3ddd0cb2"
down_revision = "b6f903208edd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rm_stochastic_total_location_risk_score",
        sa.Column("calculated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("inputs", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("project_location_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_location_id"],
            ["project_locations.id"],
        ),
        sa.PrimaryKeyConstraint("calculated_at", "project_location_id"),
    )
    op.create_index(
        "rm_stochastic_total_location_risk_score_entity_idx",
        "rm_stochastic_total_location_risk_score",
        ["project_location_id", "date"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "rm_stochastic_total_location_risk_score_entity_idx",
        table_name="rm_stochastic_total_location_risk_score",
    )
    op.drop_table("rm_stochastic_total_location_risk_score")
    # ### end Alembic commands ###
