"""remove date from ProjectLocationSiteCondition

Revision ID: 554149a9d1e3
Revises: 070209b211c7
Create Date: 2022-03-22 14:47:12.195976

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "554149a9d1e3"
down_revision = "070209b211c7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project_location_site_conditions", "date")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project_location_site_conditions",
        sa.Column("date", sa.DATE(), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
