"""Set up project safety climate multiplier table

Revision ID: 5b4ef1424f58
Revises: 1cf4ae48810e
Create Date: 2022-01-28 12:00:20.379342

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "5b4ef1424f58"
down_revision = "1cf4ae48810e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rm_project_safety_climate_multiplier",
        sa.Column("calculated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("tenant", sqlmodel.sql.sqltypes.GUID(), nullable=True),
        sa.Column("contractor_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("supervisor_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.PrimaryKeyConstraint("calculated_at", "contractor_id", "supervisor_id"),
    )
    op.execute(
        """
        INSERT INTO rm_calc_parameters (name, value) VALUES
        ('project_safety_climate_multiplier_w_sef', '0.20'),
        ('project_safety_climate_multiplier_w_csr', '0.80');
        """
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("rm_project_safety_climate_multiplier")
    op.execute(
        """
        DELETE FROM rm_calc_parameters WHERE name in (
            'project_safety_climate_multiplier_w_sef',
            'project_safety_climate_multiplier_w_csr'
        )
        """
    )
    # ### end Alembic commands ###
