"""user unique keycloak per tenant

Revision ID: 5c1568f13b50
Revises: 77c5fc1304f6
Create Date: 2022-04-04 16:43:00.717348

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "5c1568f13b50"
down_revision = "77c5fc1304f6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_users_keycloak_id", table_name="users")
    op.create_index(
        op.f("ix_users_keycloak_id"), "users", ["keycloak_id"], unique=False
    )
    op.create_index(op.f("ix_users_tenant_id"), "users", ["tenant_id"], unique=False)
    op.create_index(
        "users_tenant_keycloak_idx", "users", ["tenant_id", "keycloak_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("users_tenant_keycloak_idx", table_name="users")
    op.drop_index(op.f("ix_users_tenant_id"), table_name="users")
    op.drop_index(op.f("ix_users_keycloak_id"), table_name="users")
    op.create_index("ix_users_keycloak_id", "users", ["keycloak_id"], unique=False)
    # ### end Alembic commands ###
