"""autogenerated remove contractor name constraint

Revision ID: 69c7656bd2ea
Revises: 5c1568f13b50
Create Date: 2022-04-05 20:00:07.207615

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "69c7656bd2ea"
down_revision = "5c1568f13b50"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("contractor_name_key", "contractor", type_="unique")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("contractor_name_key", "contractor", ["name"])
    # ### end Alembic commands ###
