"""add user model

Revision ID: 747ea3663220
Revises: 0d33ccab5353
Create Date: 2022-01-21 15:01:15.886899

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "747ea3663220"
down_revision = "0d33ccab5353"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("keycloak_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("first_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("last_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_users_keycloak_id"), "users", ["keycloak_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_keycloak_id"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
