"""Add contractor_id to ContractorSafetyHistoryModel

Revision ID: 74beb09fc391
Revises: 62e64a294934
Create Date: 2022-01-24 18:05:49.994184

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "74beb09fc391"
down_revision = "62e64a294934"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "rm_contractor_safety_history",
        sa.Column("contractor_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("rm_contractor_safety_history", "contractor_id")
    # ### end Alembic commands ###
