"""dropping rm_project_site_conditions_multiplier

Revision ID: 758988c4bb11
Revises: 4cedd5425652
Create Date: 2022-02-09 09:37:20.594951

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "758988c4bb11"
down_revision = "4cedd5425652"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("rm_project_site_conditions_multiplier")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rm_project_site_conditions_multiplier",
        sa.Column(
            "calculated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "value",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("tenant", postgresql.UUID(), autoincrement=False, nullable=True),
        sa.Column("project_id", postgresql.UUID(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name="rm_project_site_conditions_multiplier_project_id_fkey",
        ),
        sa.PrimaryKeyConstraint(
            "calculated_at", name="rm_project_site_conditions_multiplier_pkey"
        ),
    )
    # ### end Alembic commands ###
