"""Add archived_at to LibraryControls

Revision ID: 76e8b1cf2281
Revises: 769ad10ec325
Create Date: 2023-05-08 16:50:32.340749

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "76e8b1cf2281"
down_revision = "769ad10ec325"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "library_controls",
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("library_controls", "archived_at")
    # ### end Alembic commands ###
