"""adding sample model to db

Revision ID: 782895fbe52e
Revises: b37c69e44f51
Create Date: 2021-12-10 14:01:31.832594

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "782895fbe52e"
down_revision = "b37c69e44f51"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "samplemodel",
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=True),
        sa.Column("sample_field_1", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("sample_field_2", sa.Integer(), nullable=True),
        sa.Column(
            "sample_field_3", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=True
        ),
        sa.Column("sample_field_4", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_samplemodel_id"), "samplemodel", ["id"], unique=False)
    op.create_index(
        op.f("ix_samplemodel_sample_field_1"),
        "samplemodel",
        ["sample_field_1"],
        unique=False,
    )
    op.create_index(
        op.f("ix_samplemodel_sample_field_2"),
        "samplemodel",
        ["sample_field_2"],
        unique=False,
    )
    op.create_index(
        op.f("ix_samplemodel_sample_field_3"),
        "samplemodel",
        ["sample_field_3"],
        unique=False,
    )
    op.create_index(
        op.f("ix_samplemodel_sample_field_4"),
        "samplemodel",
        ["sample_field_4"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_samplemodel_sample_field_4"), table_name="samplemodel")
    op.drop_index(op.f("ix_samplemodel_sample_field_3"), table_name="samplemodel")
    op.drop_index(op.f("ix_samplemodel_sample_field_2"), table_name="samplemodel")
    op.drop_index(op.f("ix_samplemodel_sample_field_1"), table_name="samplemodel")
    op.drop_index(op.f("ix_samplemodel_id"), table_name="samplemodel")
    op.drop_table("samplemodel")
    # ### end Alembic commands ###
