"""change user keycloak_id to unique

Revision ID: 78ce7f572b97
Revises: 50d2eeb2f81d
Create Date: 2022-01-27 12:04:27.264646

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "78ce7f572b97"
down_revision = "50d2eeb2f81d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_users_keycloak_id", table_name="users")
    op.create_index(op.f("ix_users_keycloak_id"), "users", ["keycloak_id"], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_keycloak_id"), table_name="users")
    op.create_index("ix_users_keycloak_id", "users", ["keycloak_id"], unique=False)
    # ### end Alembic commands ###
