"""update total task risk model

Revision ID: 7f40094f46b5
Revises: 06048c586957
Create Date: 2022-02-03 10:55:14.845250

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7f40094f46b5"
down_revision = "06048c586957"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "rm_total_task_risk_score", sa.Column("date", sa.Date(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("rm_total_task_risk_score", "date")
    # ### end Alembic commands ###
