"""adding incident model to db

Revision ID: 93ea4428c4e8
Revises: fe793e1e0461
Create Date: 2021-12-10 13:54:31.068778

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "93ea4428c4e8"
down_revision = "fe793e1e0461"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "raw_incidents",
        sa.Column(
            "centroid_source",
            sa.Enum(
                "centroid_from_client",
                "centroid_from_geocoder",
                "centroid_from_polygo",
                "centroid_from_bounding_box",
                name="centroidtype",
            ),
            nullable=True,
        ),
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("client_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("incident_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("supervisor_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("project_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("contractor", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("timestamp_created", sa.DateTime(), nullable=True),
        sa.Column("timestamp_updated", sa.DateTime(), nullable=True),
        sa.Column("incident_type", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("incident_datetime", sa.DateTime(), nullable=False),
        sa.Column("street_number", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("street", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("city", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("state", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("zipcode", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("address", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("north_latitude", sa.Float(), nullable=True),
        sa.Column("west_longitude", sa.Float(), nullable=True),
        sa.Column("south_latitude", sa.Float(), nullable=True),
        sa.Column("east_longitude", sa.Float(), nullable=True),
        sa.Column(
            "person_impacted_type", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("person_impacted", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "location_description", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("job_type_1", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("job_type_2", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("job_type_3", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "environmental_outcome", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "person_impacted_severity_outcome",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=True,
        ),
        sa.Column(
            "motor_vehicle_outcome", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "inferred_work_start_date_confidence",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=True,
        ),
        sa.Column("public_outcome", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("asset_outcome", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("task_type", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("incident_id"),
    )
    op.create_index(
        op.f("ix_raw_incidents_address"), "raw_incidents", ["address"], unique=False
    )
    op.create_index(
        op.f("ix_raw_incidents_asset_outcome"),
        "raw_incidents",
        ["asset_outcome"],
        unique=False,
    )
    op.create_index(
        op.f("ix_raw_incidents_city"), "raw_incidents", ["city"], unique=False
    )
    op.create_index(
        op.f("ix_raw_incidents_client_id"), "raw_incidents", ["client_id"], unique=False
    )
    op.create_index(
        op.f("ix_raw_incidents_contractor"),
        "raw_incidents",
        ["contractor"],
        unique=False,
    )
    op.create_index(
        op.f("ix_raw_incidents_description"),
        "raw_incidents",
        ["description"],
        unique=False,
    )
    op.create_index(
        op.f("ix_raw_incidents_east_longitude"),
        "raw_incidents",
        ["east_longitude"],
        unique=False,
    )
    op.create_index(
        op.f("ix_raw_incidents_environmental_outcome"),
        "raw_incidents",
        ["environmental_outcome"],
        unique=False,
    )
    op.create_index(op.f("ix_raw_incidents_id"), "raw_incidents", ["id"], unique=False)
    op.create_index(
        op.f("ix_raw_incidents_incident_datetime"),
        "raw_incidents",
        ["incident_datetime"],
        unique=False,
    )
    op.create_index(
        op.f("ix_raw_incidents_incident_id"),
        "raw_incidents",
        ["incident_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_raw_incidents_incident_type"),
        "raw_incidents",
        ["incident_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_raw_incidents_inferred_work_start_date_confidence"),
        "raw_incidents",
        ["inferred_work_start_date_confidence"],
        unique=False,
    )
    op.create_index(
        op.f("ix_raw_incidents_job_type_1"),
        "raw_incidents",
        ["job_type_1"],
        unique=False,
    )
    op.create_index(
        op.f("ix_raw_incidents_job_type_2"),
        "raw_incidents",
        ["job_type_2"],
        unique=False,
    )
    op.create_index(
        op.f("ix_raw_incidents_job_type_3"),
        "raw_incidents",
        ["job_type_3"],
        unique=False,
    )
    op.create_index(
        op.f("ix_raw_incidents_latitude"), "raw_incidents", ["latitude"], unique=False
    )
    op.create_index(
        op.f("ix_raw_incidents_location_description"),
        "raw_incidents",
        ["location_description"],
        unique=False,
    )
    op.create_index(
        op.f("ix_raw_incidents_longitude"), "raw_incidents", ["longitude"], unique=False
    )
    op.create_index(
        op.f("ix_raw_incidents_motor_vehicle_outcome"),
        "raw_incidents",
        ["motor_vehicle_outcome"],
        unique=False,
    )
    op.create_index(
        op.f("ix_raw_incidents_north_latitude"),
        "raw_incidents",
        ["north_latitude"],
        unique=False,
    )
    op.create_index(
        op.f("ix_raw_incidents_person_impacted"),
        "raw_incidents",
        ["person_impacted"],
        unique=False,
    )
    op.create_index(
        op.f("ix_raw_incidents_person_impacted_severity_outcome"),
        "raw_incidents",
        ["person_impacted_severity_outcome"],
        unique=False,
    )
    op.create_index(
        op.f("ix_raw_incidents_person_impacted_type"),
        "raw_incidents",
        ["person_impacted_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_raw_incidents_project_id"),
        "raw_incidents",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_raw_incidents_public_outcome"),
        "raw_incidents",
        ["public_outcome"],
        unique=False,
    )
    op.create_index(
        op.f("ix_raw_incidents_south_latitude"),
        "raw_incidents",
        ["south_latitude"],
        unique=False,
    )
    op.create_index(
        op.f("ix_raw_incidents_state"), "raw_incidents", ["state"], unique=False
    )
    op.create_index(
        op.f("ix_raw_incidents_street"), "raw_incidents", ["street"], unique=False
    )
    op.create_index(
        op.f("ix_raw_incidents_street_number"),
        "raw_incidents",
        ["street_number"],
        unique=False,
    )
    op.create_index(
        op.f("ix_raw_incidents_supervisor_id"),
        "raw_incidents",
        ["supervisor_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_raw_incidents_task_type"), "raw_incidents", ["task_type"], unique=False
    )
    op.create_index(
        op.f("ix_raw_incidents_timestamp_created"),
        "raw_incidents",
        ["timestamp_created"],
        unique=False,
    )
    op.create_index(
        op.f("ix_raw_incidents_timestamp_updated"),
        "raw_incidents",
        ["timestamp_updated"],
        unique=False,
    )
    op.create_index(
        op.f("ix_raw_incidents_west_longitude"),
        "raw_incidents",
        ["west_longitude"],
        unique=False,
    )
    op.create_index(
        op.f("ix_raw_incidents_zipcode"), "raw_incidents", ["zipcode"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_raw_incidents_zipcode"), table_name="raw_incidents")
    op.drop_index(op.f("ix_raw_incidents_west_longitude"), table_name="raw_incidents")
    op.drop_index(
        op.f("ix_raw_incidents_timestamp_updated"), table_name="raw_incidents"
    )
    op.drop_index(
        op.f("ix_raw_incidents_timestamp_created"), table_name="raw_incidents"
    )
    op.drop_index(op.f("ix_raw_incidents_task_type"), table_name="raw_incidents")
    op.drop_index(op.f("ix_raw_incidents_supervisor_id"), table_name="raw_incidents")
    op.drop_index(op.f("ix_raw_incidents_street_number"), table_name="raw_incidents")
    op.drop_index(op.f("ix_raw_incidents_street"), table_name="raw_incidents")
    op.drop_index(op.f("ix_raw_incidents_state"), table_name="raw_incidents")
    op.drop_index(op.f("ix_raw_incidents_south_latitude"), table_name="raw_incidents")
    op.drop_index(op.f("ix_raw_incidents_public_outcome"), table_name="raw_incidents")
    op.drop_index(op.f("ix_raw_incidents_project_id"), table_name="raw_incidents")
    op.drop_index(
        op.f("ix_raw_incidents_person_impacted_type"), table_name="raw_incidents"
    )
    op.drop_index(
        op.f("ix_raw_incidents_person_impacted_severity_outcome"),
        table_name="raw_incidents",
    )
    op.drop_index(op.f("ix_raw_incidents_person_impacted"), table_name="raw_incidents")
    op.drop_index(op.f("ix_raw_incidents_north_latitude"), table_name="raw_incidents")
    op.drop_index(
        op.f("ix_raw_incidents_motor_vehicle_outcome"), table_name="raw_incidents"
    )
    op.drop_index(op.f("ix_raw_incidents_longitude"), table_name="raw_incidents")
    op.drop_index(
        op.f("ix_raw_incidents_location_description"), table_name="raw_incidents"
    )
    op.drop_index(op.f("ix_raw_incidents_latitude"), table_name="raw_incidents")
    op.drop_index(op.f("ix_raw_incidents_job_type_3"), table_name="raw_incidents")
    op.drop_index(op.f("ix_raw_incidents_job_type_2"), table_name="raw_incidents")
    op.drop_index(op.f("ix_raw_incidents_job_type_1"), table_name="raw_incidents")
    op.drop_index(
        op.f("ix_raw_incidents_inferred_work_start_date_confidence"),
        table_name="raw_incidents",
    )
    op.drop_index(op.f("ix_raw_incidents_incident_type"), table_name="raw_incidents")
    op.drop_index(op.f("ix_raw_incidents_incident_id"), table_name="raw_incidents")
    op.drop_index(
        op.f("ix_raw_incidents_incident_datetime"), table_name="raw_incidents"
    )
    op.drop_index(op.f("ix_raw_incidents_id"), table_name="raw_incidents")
    op.drop_index(
        op.f("ix_raw_incidents_environmental_outcome"), table_name="raw_incidents"
    )
    op.drop_index(op.f("ix_raw_incidents_east_longitude"), table_name="raw_incidents")
    op.drop_index(op.f("ix_raw_incidents_description"), table_name="raw_incidents")
    op.drop_index(op.f("ix_raw_incidents_contractor"), table_name="raw_incidents")
    op.drop_index(op.f("ix_raw_incidents_client_id"), table_name="raw_incidents")
    op.drop_index(op.f("ix_raw_incidents_city"), table_name="raw_incidents")
    op.drop_index(op.f("ix_raw_incidents_asset_outcome"), table_name="raw_incidents")
    op.drop_index(op.f("ix_raw_incidents_address"), table_name="raw_incidents")
    op.drop_table("raw_incidents")
    op.execute("DROP TYPE centroidtype")
    # ### end Alembic commands ###
