"""refactor task specific models

Revision ID: 9d00fb5ce7a0
Revises: fb31bc54c5d3
Create Date: 2022-02-01 16:18:17.600333

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "9d00fb5ce7a0"
down_revision = "fb31bc54c5d3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "rm_task_specific_safety_climate_multiplier",
        sa.Column("library_task_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
    )
    op.drop_constraint(
        "rm_task_specific_safety_climate_multiplier_project_task_id_fkey",
        "rm_task_specific_safety_climate_multiplier",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "rm_task_specific_safety_climate_multiplier_library_task_id_fkey",
        "rm_task_specific_safety_climate_multiplier",
        "library_tasks",
        ["library_task_id"],
        ["id"],
    )
    op.drop_column("rm_task_specific_safety_climate_multiplier", "project_task_id")
    # Other table
    op.alter_column(
        "rm_task_specific_site_conditions_multiplier",
        "date",
        existing_type=sa.DateTime(),
        type_=sa.Date(),
    )
    op.alter_column(
        "rm_task_specific_risk_score",
        "date",
        existing_type=sa.DateTime(),
        type_=sa.Date(),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "rm_task_specific_site_conditions_multiplier",
        "date",
        type_=sa.DateTime(),
        existing_type=sa.Date(),
    )
    op.alter_column(
        "rm_task_specific_risk_score",
        "date",
        type_=sa.DateTime(),
        existing_type=sa.Date(),
    )
    # Other table
    op.add_column(
        "rm_task_specific_safety_climate_multiplier",
        sa.Column(
            "project_task_id", postgresql.UUID(), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(
        "rm_task_specific_safety_climate_multiplier_library_task_id_fkey",
        "rm_task_specific_safety_climate_multiplier",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "rm_task_specific_safety_climate_multiplier_project_task_id_fkey",
        "rm_task_specific_safety_climate_multiplier",
        "project_location_tasks",
        ["project_task_id"],
        ["id"],
    )
    op.drop_column("rm_task_specific_safety_climate_multiplier", "library_task_id")
    # ### end Alembic commands ###
