"""Add Global Contrator Project History Baseline table

Revision ID: a11127904f4d
Revises: 1b1325849463
Create Date: 2022-01-17 15:41:54.132502

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a11127904f4d"
down_revision = "1b1325849463"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rm_gbl_contractor_project_history_bsl",
        sa.Column("calculated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("calculated_at"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("rm_gbl_contractor_project_history_bsl")
    # ### end Alembic commands ###
