"""add library division and region link tables

Revision ID: a62ea468c7bb
Revises: 672c8c97558a
Create Date: 2022-09-30 14:33:22.359830

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "a62ea468c7bb"
down_revision = "374c8bcbb81d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "library_division_tenant_link",
        sa.Column("library_division_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("tenant_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["library_division_id"],
            ["library_divisions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("library_division_id", "tenant_id"),
    )
    op.create_table(
        "library_region_tenant_link",
        sa.Column("library_region_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("tenant_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["library_region_id"],
            ["library_regions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("library_region_id", "tenant_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("library_region_tenant_link")
    op.drop_table("library_division_tenant_link")
    # ### end Alembic commands ###
