"""Removed LibraryTaskSiteConditionLink dead table

Revision ID: aa14d4658694
Revises: bd48f8d64d31
Create Date: 2023-03-28 15:55:40.179049

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "aa14d4658694"
down_revision = "bd48f8d64d31"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("library_task_site_conditions")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "library_task_site_conditions",
        sa.Column(
            "library_site_condition_id",
            postgresql.UUID(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "library_task_id", postgresql.UUID(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["library_site_condition_id"],
            ["library_site_conditions.id"],
            name="library_task_site_conditions_library_site_condition_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["library_task_id"],
            ["library_tasks.id"],
            name="library_task_site_conditions_library_task_id_fkey",
        ),
        sa.PrimaryKeyConstraint(
            "library_site_condition_id",
            "library_task_id",
            name="library_task_site_conditions_pkey",
        ),
    )
    # ### end Alembic commands ###
