"""Adding inputs to RiskModelBase

Revision ID: ae4ef53e609b
Revises: 33a1b906f4a2
Create Date: 2022-03-08 13:57:38.431654

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "ae4ef53e609b"
down_revision = "33a1b906f4a2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "rm_average_contractor_safety_score",
        sa.Column("inputs", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "rm_average_supervisor_engagement_factor",
        sa.Column("inputs", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "rm_contractor_project_execution",
        sa.Column("inputs", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "rm_contractor_safety_history",
        sa.Column("inputs", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "rm_contractor_safety_rating",
        sa.Column("inputs", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "rm_contractor_safety_score",
        sa.Column("inputs", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "rm_gbl_contractor_project_history_bsl",
        sa.Column("inputs", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "rm_gbl_contractor_project_history_bsl_stddev",
        sa.Column("inputs", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "rm_manually_added_site_conditions",
        sa.Column("inputs", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "rm_project_location_safety_climate_multiplier",
        sa.Column("inputs", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "rm_project_location_total_task_risk_score",
        sa.Column("inputs", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "rm_project_site_conditions_multiplier",
        sa.Column("inputs", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "rm_project_total_task_risk_score",
        sa.Column("inputs", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "rm_stddev_contractor_safety_score",
        sa.Column("inputs", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "rm_stddev_supervisor_engagement_factor",
        sa.Column("inputs", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "rm_supervisor_engagement_factor",
        sa.Column("inputs", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "rm_surface_project_project_location_risk_scores",
        sa.Column("inputs", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "rm_surface_total_task_task_specific_risk_ranking",
        sa.Column("inputs", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "rm_task_specific_risk_score",
        sa.Column("inputs", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "rm_task_specific_safety_climate_multiplier",
        sa.Column("inputs", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "rm_task_specific_site_conditions_multiplier",
        sa.Column("inputs", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "rm_total_project_location_risk_score",
        sa.Column("inputs", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "rm_total_project_risk_score",
        sa.Column("inputs", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("rm_total_project_risk_score", "inputs")
    op.drop_column("rm_total_project_location_risk_score", "inputs")
    op.drop_column("rm_task_specific_site_conditions_multiplier", "inputs")
    op.drop_column("rm_task_specific_safety_climate_multiplier", "inputs")
    op.drop_column("rm_task_specific_risk_score", "inputs")
    op.drop_column("rm_surface_total_task_task_specific_risk_ranking", "inputs")
    op.drop_column("rm_surface_project_project_location_risk_scores", "inputs")
    op.drop_column("rm_supervisor_engagement_factor", "inputs")
    op.drop_column("rm_stddev_supervisor_engagement_factor", "inputs")
    op.drop_column("rm_stddev_contractor_safety_score", "inputs")
    op.drop_column("rm_project_total_task_risk_score", "inputs")
    op.drop_column("rm_project_site_conditions_multiplier", "inputs")
    op.drop_column("rm_project_location_total_task_risk_score", "inputs")
    op.drop_column("rm_project_location_safety_climate_multiplier", "inputs")
    op.drop_column("rm_manually_added_site_conditions", "inputs")
    op.drop_column("rm_gbl_contractor_project_history_bsl_stddev", "inputs")
    op.drop_column("rm_gbl_contractor_project_history_bsl", "inputs")
    op.drop_column("rm_contractor_safety_score", "inputs")
    op.drop_column("rm_contractor_safety_rating", "inputs")
    op.drop_column("rm_contractor_safety_history", "inputs")
    op.drop_column("rm_contractor_project_execution", "inputs")
    op.drop_column("rm_average_supervisor_engagement_factor", "inputs")
    op.drop_column("rm_average_contractor_safety_score", "inputs")
    # ### end Alembic commands ###
