"""adding observation model to db

Revision ID: b37c69e44f51
Revises: 93ea4428c4e8
Create Date: 2021-12-10 14:00:25.142374

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects.postgresql import ENUM

# revision identifiers, used by Alembic.
revision = "b37c69e44f51"
down_revision = "93ea4428c4e8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "observation",
        sa.Column(
            "centroid_source",
            ENUM(
                "centroid_from_client",
                "centroid_from_geocoder",
                "centroid_from_polygo",
                "centroid_from_bounding_box",
                name="centroidtype",
                create_type=False,
            ),
            nullable=True,
        ),
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("observation_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("timestamp_created", sa.DateTime(), nullable=True),
        sa.Column("timestamp_updated", sa.DateTime(), nullable=True),
        sa.Column("observation_datetime", sa.DateTime(), nullable=True),
        sa.Column("action_datetime", sa.DateTime(), nullable=True),
        sa.Column("response_specific_action_datetime", sa.DateTime(), nullable=True),
        sa.Column("client_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("supervisor_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("project_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("action_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "response_specific_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "observation_type", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "person_type_reporting", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "contractor_involved", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("location_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("street", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("city", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("state", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("address", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("job_type_1", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("job_type_2", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("job_type_3", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("task_type", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("task_detail", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "observation_comments", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("action_type", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("action_category", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("action_topic", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("response", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "response_specific_action_comments",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("observation_id"),
    )
    op.create_index(
        op.f("ix_observation_action_category"),
        "observation",
        ["action_category"],
        unique=False,
    )
    op.create_index(
        op.f("ix_observation_action_datetime"),
        "observation",
        ["action_datetime"],
        unique=False,
    )
    op.create_index(
        op.f("ix_observation_action_id"), "observation", ["action_id"], unique=False
    )
    op.create_index(
        op.f("ix_observation_action_topic"),
        "observation",
        ["action_topic"],
        unique=False,
    )
    op.create_index(
        op.f("ix_observation_action_type"), "observation", ["action_type"], unique=False
    )
    op.create_index(
        op.f("ix_observation_address"), "observation", ["address"], unique=False
    )
    op.create_index(op.f("ix_observation_city"), "observation", ["city"], unique=False)
    op.create_index(
        op.f("ix_observation_client_id"), "observation", ["client_id"], unique=False
    )
    op.create_index(
        op.f("ix_observation_contractor_involved"),
        "observation",
        ["contractor_involved"],
        unique=False,
    )
    op.create_index(op.f("ix_observation_id"), "observation", ["id"], unique=False)
    op.create_index(
        op.f("ix_observation_job_type_1"), "observation", ["job_type_1"], unique=False
    )
    op.create_index(
        op.f("ix_observation_job_type_2"), "observation", ["job_type_2"], unique=False
    )
    op.create_index(
        op.f("ix_observation_job_type_3"), "observation", ["job_type_3"], unique=False
    )
    op.create_index(
        op.f("ix_observation_latitude"), "observation", ["latitude"], unique=False
    )
    op.create_index(
        op.f("ix_observation_location_name"),
        "observation",
        ["location_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_observation_longitude"), "observation", ["longitude"], unique=False
    )
    op.create_index(
        op.f("ix_observation_observation_comments"),
        "observation",
        ["observation_comments"],
        unique=False,
    )
    op.create_index(
        op.f("ix_observation_observation_datetime"),
        "observation",
        ["observation_datetime"],
        unique=False,
    )
    op.create_index(
        op.f("ix_observation_observation_id"),
        "observation",
        ["observation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_observation_observation_type"),
        "observation",
        ["observation_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_observation_person_type_reporting"),
        "observation",
        ["person_type_reporting"],
        unique=False,
    )
    op.create_index(
        op.f("ix_observation_project_id"), "observation", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_observation_response"), "observation", ["response"], unique=False
    )
    op.create_index(
        op.f("ix_observation_response_specific_action_comments"),
        "observation",
        ["response_specific_action_comments"],
        unique=False,
    )
    op.create_index(
        op.f("ix_observation_response_specific_action_datetime"),
        "observation",
        ["response_specific_action_datetime"],
        unique=False,
    )
    op.create_index(
        op.f("ix_observation_response_specific_id"),
        "observation",
        ["response_specific_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_observation_state"), "observation", ["state"], unique=False
    )
    op.create_index(
        op.f("ix_observation_street"), "observation", ["street"], unique=False
    )
    op.create_index(
        op.f("ix_observation_supervisor_id"),
        "observation",
        ["supervisor_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_observation_task_detail"), "observation", ["task_detail"], unique=False
    )
    op.create_index(
        op.f("ix_observation_task_type"), "observation", ["task_type"], unique=False
    )
    op.create_index(
        op.f("ix_observation_timestamp_created"),
        "observation",
        ["timestamp_created"],
        unique=False,
    )
    op.create_index(
        op.f("ix_observation_timestamp_updated"),
        "observation",
        ["timestamp_updated"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_observation_timestamp_updated"), table_name="observation")
    op.drop_index(op.f("ix_observation_timestamp_created"), table_name="observation")
    op.drop_index(op.f("ix_observation_task_type"), table_name="observation")
    op.drop_index(op.f("ix_observation_task_detail"), table_name="observation")
    op.drop_index(op.f("ix_observation_supervisor_id"), table_name="observation")
    op.drop_index(op.f("ix_observation_street"), table_name="observation")
    op.drop_index(op.f("ix_observation_state"), table_name="observation")
    op.drop_index(op.f("ix_observation_response_specific_id"), table_name="observation")
    op.drop_index(
        op.f("ix_observation_response_specific_action_datetime"),
        table_name="observation",
    )
    op.drop_index(
        op.f("ix_observation_response_specific_action_comments"),
        table_name="observation",
    )
    op.drop_index(op.f("ix_observation_response"), table_name="observation")
    op.drop_index(op.f("ix_observation_project_id"), table_name="observation")
    op.drop_index(
        op.f("ix_observation_person_type_reporting"), table_name="observation"
    )
    op.drop_index(op.f("ix_observation_observation_type"), table_name="observation")
    op.drop_index(op.f("ix_observation_observation_id"), table_name="observation")
    op.drop_index(op.f("ix_observation_observation_datetime"), table_name="observation")
    op.drop_index(op.f("ix_observation_observation_comments"), table_name="observation")
    op.drop_index(op.f("ix_observation_longitude"), table_name="observation")
    op.drop_index(op.f("ix_observation_location_name"), table_name="observation")
    op.drop_index(op.f("ix_observation_latitude"), table_name="observation")
    op.drop_index(op.f("ix_observation_job_type_3"), table_name="observation")
    op.drop_index(op.f("ix_observation_job_type_2"), table_name="observation")
    op.drop_index(op.f("ix_observation_job_type_1"), table_name="observation")
    op.drop_index(op.f("ix_observation_id"), table_name="observation")
    op.drop_index(op.f("ix_observation_contractor_involved"), table_name="observation")
    op.drop_index(op.f("ix_observation_client_id"), table_name="observation")
    op.drop_index(op.f("ix_observation_city"), table_name="observation")
    op.drop_index(op.f("ix_observation_address"), table_name="observation")
    op.drop_index(op.f("ix_observation_action_type"), table_name="observation")
    op.drop_index(op.f("ix_observation_action_topic"), table_name="observation")
    op.drop_index(op.f("ix_observation_action_id"), table_name="observation")
    op.drop_index(op.f("ix_observation_action_datetime"), table_name="observation")
    op.drop_index(op.f("ix_observation_action_category"), table_name="observation")
    op.drop_table("observation")
    # ### end Alembic commands ###
