"""add archived_at to daily report

Revision ID: b9e24c5dd6b6
Revises: 62765c0a33d8
Create Date: 2022-02-18 10:43:21.596898

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b9e24c5dd6b6"
down_revision = "62765c0a33d8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "daily_reports",
        sa.Column("archived_at", sa.TIMESTAMP(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("daily_reports", "archived_at")
    # ### end Alembic commands ###
