"""Introduce WPKG fields

Revision ID: bb88fd6bc38c
Revises: 444fa996c207
Create Date: 2022-08-02 11:42:44.395563

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "bb88fd6bc38c"
down_revision = "444fa996c207"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects",
        sa.Column(
            "meta_attributes", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.add_column(
        "projects",
        sa.Column("customer_status", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "projects",
        sa.Column(
            "work_package_type", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )
    op.alter_column("projects", "number", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "projects", "library_region_id", existing_type=postgresql.UUID(), nullable=True
    )
    op.alter_column(
        "projects",
        "library_division_id",
        existing_type=postgresql.UUID(),
        nullable=True,
    )
    op.alter_column(
        "projects", "manager_id", existing_type=postgresql.UUID(), nullable=True
    )
    op.alter_column(
        "projects", "contractor_id", existing_type=postgresql.UUID(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "projects", "contractor_id", existing_type=postgresql.UUID(), nullable=False
    )
    op.alter_column(
        "projects", "manager_id", existing_type=postgresql.UUID(), nullable=False
    )
    op.alter_column(
        "projects",
        "library_division_id",
        existing_type=postgresql.UUID(),
        nullable=False,
    )
    op.alter_column(
        "projects", "library_region_id", existing_type=postgresql.UUID(), nullable=False
    )
    op.alter_column("projects", "number", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_column("projects", "work_package_type")
    op.drop_column("projects", "customer_status")
    op.drop_column("projects", "meta_attributes")
    # ### end Alembic commands ###
