"""Add archived_at to library tasks

Revision ID: bdb108212926
Revises: bee360fe63b9
Create Date: 2023-04-18 10:30:15.163939

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "bdb108212926"
down_revision = "bee360fe63b9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "library_tasks",
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.alter_column(
        "library_tasks", "unique_task_id", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "library_tasks", "unique_task_id", existing_type=sa.VARCHAR(), nullable=True
    )
    op.drop_column("library_tasks", "archived_at")
    # ### end Alembic commands ###
