"""updating risk model tables

Revision ID: c0165a2a8baa
Revises: ecd2d6dacb9b
Create Date: 2022-01-21 12:04:58.674025

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "c0165a2a8baa"
down_revision = "ecd2d6dacb9b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "rm_contractor_project_execution",
        sa.Column("tenant", sqlmodel.sql.sqltypes.GUID(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("rm_contractor_project_execution", "tenant")
    # ### end Alembic commands ###
