"""Added indexes to the risk model entities

Revision ID: c2266c2ea9e7
Revises: dbb1276bc2bc
Create Date: 2022-04-22 00:56:54.040958

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "c2266c2ea9e7"
down_revision = "dbb1276bc2bc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "rm_average_contractor_safety_score_entity_idx",
        "rm_average_contractor_safety_score",
        ["tenant_id"],
        unique=False,
    )
    op.create_index(
        "rm_average_supervisor_engagement_factor_entity_idx",
        "rm_average_supervisor_engagement_factor",
        ["tenant_id"],
        unique=False,
    )
    op.create_index(
        "rm_contractor_project_execution_entity_idx",
        "rm_contractor_project_execution",
        ["contractor_id"],
        unique=False,
    )
    op.create_index(
        "rm_contractor_safety_history_entity_idx",
        "rm_contractor_safety_history",
        ["contractor_id"],
        unique=False,
    )
    op.create_index(
        "rm_contractor_safety_rating_entity_idx",
        "rm_contractor_safety_rating",
        ["contractor_id"],
        unique=False,
    )
    op.create_index(
        "rm_contractor_safety_score_entity_idx",
        "rm_contractor_safety_score",
        ["contractor_id"],
        unique=False,
    )
    op.create_index(
        "rm_gbl_contractor_project_history_bsl_entity_idx",
        "rm_gbl_contractor_project_history_bsl",
        ["tenant_id"],
        unique=False,
    )
    op.create_index(
        "rm_gbl_contractor_project_history_bsl_stddev_entity_idx",
        "rm_gbl_contractor_project_history_bsl_stddev",
        ["tenant_id"],
        unique=False,
    )
    op.create_index(
        "rm_manually_added_site_conditions_entity_idx",
        "rm_manually_added_site_conditions",
        ["project_location_id"],
        unique=False,
    )
    op.create_index(
        "rm_project_location_safety_climate_multiplier_entity_idx",
        "rm_project_location_safety_climate_multiplier",
        ["project_location_id"],
        unique=False,
    )
    op.create_index(
        "rm_project_location_total_task_risk_score_entity_idx",
        "rm_project_location_total_task_risk_score",
        ["project_location_id", "date"],
        unique=False,
    )
    op.create_index(
        "rm_project_site_conditions_multiplier_entity_idx",
        "rm_project_site_conditions_multiplier",
        ["project_location_id", "date"],
        unique=False,
    )
    op.create_index(
        "rm_project_total_task_risk_score_entity_idx",
        "rm_project_total_task_risk_score",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        "rm_stddev_contractor_safety_score_entity_idx",
        "rm_stddev_contractor_safety_score",
        ["tenant_id"],
        unique=False,
    )
    op.create_index(
        "rm_stddev_supervisor_engagement_factor_entity_idx",
        "rm_stddev_supervisor_engagement_factor",
        ["tenant_id"],
        unique=False,
    )
    op.create_index(
        "rm_supervisor_engagement_factor_entity_idx",
        "rm_supervisor_engagement_factor",
        ["supervisor_id"],
        unique=False,
    )
    op.create_index(
        "rm_task_specific_risk_score_entity_idx",
        "rm_task_specific_risk_score",
        ["project_task_id", "date"],
        unique=False,
    )
    op.create_index(
        "rm_task_specific_safety_climate_multiplier_entity_idx",
        "rm_task_specific_safety_climate_multiplier",
        ["library_task_id"],
        unique=False,
    )
    op.create_index(
        "rm_task_specific_site_conditions_multiplier_entity_idx",
        "rm_task_specific_site_conditions_multiplier",
        ["project_task_id", "date"],
        unique=False,
    )
    op.create_index(
        "rm_total_project_location_risk_score_entity_idx",
        "rm_total_project_location_risk_score",
        ["project_location_id", "date"],
        unique=False,
    )
    op.create_index(
        "rm_total_project_risk_score_entity_idx",
        "rm_total_project_risk_score",
        ["project_id", "date"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "rm_total_project_risk_score_entity_idx",
        table_name="rm_total_project_risk_score",
    )
    op.drop_index(
        "rm_total_project_location_risk_score_entity_idx",
        table_name="rm_total_project_location_risk_score",
    )
    op.drop_index(
        "rm_task_specific_site_conditions_multiplier_entity_idx",
        table_name="rm_task_specific_site_conditions_multiplier",
    )
    op.drop_index(
        "rm_task_specific_safety_climate_multiplier_entity_idx",
        table_name="rm_task_specific_safety_climate_multiplier",
    )
    op.drop_index(
        "rm_task_specific_risk_score_entity_idx",
        table_name="rm_task_specific_risk_score",
    )
    op.drop_index(
        "rm_supervisor_engagement_factor_entity_idx",
        table_name="rm_supervisor_engagement_factor",
    )
    op.drop_index(
        "rm_stddev_supervisor_engagement_factor_entity_idx",
        table_name="rm_stddev_supervisor_engagement_factor",
    )
    op.drop_index(
        "rm_stddev_contractor_safety_score_entity_idx",
        table_name="rm_stddev_contractor_safety_score",
    )
    op.drop_index(
        "rm_project_total_task_risk_score_entity_idx",
        table_name="rm_project_total_task_risk_score",
    )
    op.drop_index(
        "rm_project_site_conditions_multiplier_entity_idx",
        table_name="rm_project_site_conditions_multiplier",
    )
    op.drop_index(
        "rm_project_location_total_task_risk_score_entity_idx",
        table_name="rm_project_location_total_task_risk_score",
    )
    op.drop_index(
        "rm_project_location_safety_climate_multiplier_entity_idx",
        table_name="rm_project_location_safety_climate_multiplier",
    )
    op.drop_index(
        "rm_manually_added_site_conditions_entity_idx",
        table_name="rm_manually_added_site_conditions",
    )
    op.drop_index(
        "rm_gbl_contractor_project_history_bsl_stddev_entity_idx",
        table_name="rm_gbl_contractor_project_history_bsl_stddev",
    )
    op.drop_index(
        "rm_gbl_contractor_project_history_bsl_entity_idx",
        table_name="rm_gbl_contractor_project_history_bsl",
    )
    op.drop_index(
        "rm_contractor_safety_score_entity_idx", table_name="rm_contractor_safety_score"
    )
    op.drop_index(
        "rm_contractor_safety_rating_entity_idx",
        table_name="rm_contractor_safety_rating",
    )
    op.drop_index(
        "rm_contractor_safety_history_entity_idx",
        table_name="rm_contractor_safety_history",
    )
    op.drop_index(
        "rm_contractor_project_execution_entity_idx",
        table_name="rm_contractor_project_execution",
    )
    op.drop_index(
        "rm_average_supervisor_engagement_factor_entity_idx",
        table_name="rm_average_supervisor_engagement_factor",
    )
    op.drop_index(
        "rm_average_contractor_safety_score_entity_idx",
        table_name="rm_average_contractor_safety_score",
    )
    # ### end Alembic commands ###
