"""Add Global Contrator Project History Baseline STDDEV table

Revision ID: c58c98ba4140
Revises: a11127904f4d
Create Date: 2022-01-17 18:44:42.412770

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c58c98ba4140"
down_revision = "a11127904f4d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rm_gbl_contractor_project_history_bsl_stddev",
        sa.Column("calculated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("calculated_at"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("rm_gbl_contractor_project_history_bsl_stddev")
    # ### end Alembic commands ###
