"""Initial migration

Revision ID: c703c8abd734
Revises:
Create Date: 2021-12-01 10:13:25.007175

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "c703c8abd734"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "controls",
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_controls_id"), "controls", ["id"], unique=False)
    op.create_index(op.f("ix_controls_name"), "controls", ["name"], unique=False)
    op.create_table(
        "hazards",
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_hazards_id"), "hazards", ["id"], unique=False)
    op.create_index(op.f("ix_hazards_name"), "hazards", ["name"], unique=False)
    op.create_table(
        "projects",
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_projects_end_date"), "projects", ["end_date"], unique=False
    )
    op.create_index(op.f("ix_projects_id"), "projects", ["id"], unique=False)
    op.create_index(op.f("ix_projects_name"), "projects", ["name"], unique=False)
    op.create_index(
        op.f("ix_projects_start_date"), "projects", ["start_date"], unique=False
    )
    op.create_table(
        "site_conditions",
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_site_conditions_id"), "site_conditions", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_site_conditions_name"), "site_conditions", ["name"], unique=False
    )
    op.create_table(
        "tasks",
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tasks_id"), "tasks", ["id"], unique=False)
    op.create_index(op.f("ix_tasks_name"), "tasks", ["name"], unique=False)
    op.create_table(
        "hazard_control_link",
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=True),
        sa.Column("hazard_id", sqlmodel.sql.sqltypes.GUID(), nullable=True),
        sa.Column("control_id", sqlmodel.sql.sqltypes.GUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["control_id"],
            ["controls.id"],
        ),
        sa.ForeignKeyConstraint(
            ["hazard_id"],
            ["hazards.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_hazard_control_link_control_id"),
        "hazard_control_link",
        ["control_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_hazard_control_link_hazard_id"),
        "hazard_control_link",
        ["hazard_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_hazard_control_link_id"), "hazard_control_link", ["id"], unique=False
    )
    op.create_table(
        "project_locations",
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("project_id", sqlmodel.sql.sqltypes.GUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_project_locations_id"), "project_locations", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_project_locations_name"), "project_locations", ["name"], unique=False
    )
    op.create_index(
        op.f("ix_project_locations_project_id"),
        "project_locations",
        ["project_id"],
        unique=False,
    )
    op.create_table(
        "site_condition_hazard_link",
        sa.Column("site_condition_id", sqlmodel.sql.sqltypes.GUID(), nullable=True),
        sa.Column("hazard_id", sqlmodel.sql.sqltypes.GUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["hazard_id"],
            ["hazards.id"],
        ),
        sa.ForeignKeyConstraint(
            ["site_condition_id"],
            ["site_conditions.id"],
        ),
        sa.PrimaryKeyConstraint("site_condition_id", "hazard_id"),
    )
    op.create_index(
        op.f("ix_site_condition_hazard_link_hazard_id"),
        "site_condition_hazard_link",
        ["hazard_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_site_condition_hazard_link_site_condition_id"),
        "site_condition_hazard_link",
        ["site_condition_id"],
        unique=False,
    )
    op.create_table(
        "task_hazard_link",
        sa.Column("task_id", sqlmodel.sql.sqltypes.GUID(), nullable=True),
        sa.Column("hazard_id", sqlmodel.sql.sqltypes.GUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["hazard_id"],
            ["hazards.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
        ),
        sa.PrimaryKeyConstraint("task_id", "hazard_id"),
    )
    op.create_index(
        op.f("ix_task_hazard_link_hazard_id"),
        "task_hazard_link",
        ["hazard_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_task_hazard_link_task_id"),
        "task_hazard_link",
        ["task_id"],
        unique=False,
    )
    op.create_table(
        "project_location_site_condition_link",
        sa.Column("project_location_id", sqlmodel.sql.sqltypes.GUID(), nullable=True),
        sa.Column("site_condition_id", sqlmodel.sql.sqltypes.GUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_location_id"],
            ["project_locations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["site_condition_id"],
            ["site_conditions.id"],
        ),
        sa.PrimaryKeyConstraint("project_location_id", "site_condition_id"),
    )
    op.create_index(
        op.f("ix_project_location_site_condition_link_project_location_id"),
        "project_location_site_condition_link",
        ["project_location_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_location_site_condition_link_site_condition_id"),
        "project_location_site_condition_link",
        ["site_condition_id"],
        unique=False,
    )
    op.create_table(
        "project_location_task_link",
        sa.Column("project_location_id", sqlmodel.sql.sqltypes.GUID(), nullable=True),
        sa.Column("task_id", sqlmodel.sql.sqltypes.GUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_location_id"],
            ["project_locations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
        ),
        sa.PrimaryKeyConstraint("project_location_id", "task_id"),
    )
    op.create_index(
        op.f("ix_project_location_task_link_project_location_id"),
        "project_location_task_link",
        ["project_location_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_location_task_link_task_id"),
        "project_location_task_link",
        ["task_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_project_location_task_link_task_id"),
        table_name="project_location_task_link",
    )
    op.drop_index(
        op.f("ix_project_location_task_link_project_location_id"),
        table_name="project_location_task_link",
    )
    op.drop_table("project_location_task_link")
    op.drop_index(
        op.f("ix_project_location_site_condition_link_site_condition_id"),
        table_name="project_location_site_condition_link",
    )
    op.drop_index(
        op.f("ix_project_location_site_condition_link_project_location_id"),
        table_name="project_location_site_condition_link",
    )
    op.drop_table("project_location_site_condition_link")
    op.drop_index(op.f("ix_task_hazard_link_task_id"), table_name="task_hazard_link")
    op.drop_index(op.f("ix_task_hazard_link_hazard_id"), table_name="task_hazard_link")
    op.drop_table("task_hazard_link")
    op.drop_index(
        op.f("ix_site_condition_hazard_link_site_condition_id"),
        table_name="site_condition_hazard_link",
    )
    op.drop_index(
        op.f("ix_site_condition_hazard_link_hazard_id"),
        table_name="site_condition_hazard_link",
    )
    op.drop_table("site_condition_hazard_link")
    op.drop_index(
        op.f("ix_project_locations_project_id"), table_name="project_locations"
    )
    op.drop_index(op.f("ix_project_locations_name"), table_name="project_locations")
    op.drop_index(op.f("ix_project_locations_id"), table_name="project_locations")
    op.drop_table("project_locations")
    op.drop_index(op.f("ix_hazard_control_link_id"), table_name="hazard_control_link")
    op.drop_index(
        op.f("ix_hazard_control_link_hazard_id"), table_name="hazard_control_link"
    )
    op.drop_index(
        op.f("ix_hazard_control_link_control_id"), table_name="hazard_control_link"
    )
    op.drop_table("hazard_control_link")
    op.drop_index(op.f("ix_tasks_name"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_id"), table_name="tasks")
    op.drop_table("tasks")
    op.drop_index(op.f("ix_site_conditions_name"), table_name="site_conditions")
    op.drop_index(op.f("ix_site_conditions_id"), table_name="site_conditions")
    op.drop_table("site_conditions")
    op.drop_index(op.f("ix_projects_start_date"), table_name="projects")
    op.drop_index(op.f("ix_projects_name"), table_name="projects")
    op.drop_index(op.f("ix_projects_id"), table_name="projects")
    op.drop_index(op.f("ix_projects_end_date"), table_name="projects")
    op.drop_table("projects")
    op.drop_index(op.f("ix_hazards_name"), table_name="hazards")
    op.drop_index(op.f("ix_hazards_id"), table_name="hazards")
    op.drop_table("hazards")
    op.drop_index(op.f("ix_controls_name"), table_name="controls")
    op.drop_index(op.f("ix_controls_id"), table_name="controls")
    op.drop_table("controls")
    # ### end Alembic commands ###
