"""re-adding rm_project_site_conditions_multiplier

Revision ID: d068b39629f5
Revises: 758988c4bb11
Create Date: 2022-02-09 09:38:43.728394

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "d068b39629f5"
down_revision = "758988c4bb11"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rm_project_site_conditions_multiplier",
        sa.Column("calculated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("tenant", sqlmodel.sql.sqltypes.GUID(), nullable=True),
        sa.Column("project_location_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_location_id"],
            ["project_locations.id"],
        ),
        sa.PrimaryKeyConstraint("calculated_at"),
    )
    op.add_column(
        "rm_total_project_location_risk_score",
        sa.Column("date", sa.Date(), nullable=False),
    )
    op.add_column(
        "rm_total_project_risk_score", sa.Column("date", sa.Date(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("rm_project_site_conditions_multiplier")
    op.drop_column("rm_total_project_risk_score", "date")
    op.drop_column("rm_total_project_location_risk_score", "date")
    # ### end Alembic commands ###
