"""updated project location safety climate multiplier

Revision ID: d7cd809a77f9
Revises: cbe705a47b64
Create Date: 2022-02-10 18:50:16.464189

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "d7cd809a77f9"
down_revision = "cbe705a47b64"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rm_project_location_safety_climate_multiplier",
        sa.Column("calculated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("tenant", sqlmodel.sql.sqltypes.GUID(), nullable=True),
        sa.Column("project_location_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("contractor_id", sqlmodel.sql.sqltypes.GUID(), nullable=True),
        sa.Column("supervisor_id", sqlmodel.sql.sqltypes.GUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_location_id"],
            ["project_locations.id"],
        ),
        sa.PrimaryKeyConstraint("calculated_at"),
    )
    op.drop_table("rm_project_safety_climate_multiplier")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rm_project_safety_climate_multiplier",
        sa.Column(
            "calculated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "value",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("tenant", postgresql.UUID(), autoincrement=False, nullable=True),
        sa.Column(
            "contractor_id", postgresql.UUID(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "supervisor_id", postgresql.UUID(), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint(
            "calculated_at",
            "contractor_id",
            "supervisor_id",
            name="rm_project_safety_climate_multiplier_pkey",
        ),
    )
    op.drop_table("rm_project_location_safety_climate_multiplier")
    # ### end Alembic commands ###
