"""adding tenant_id to two global fields

Revision ID: deca299cc7f2
Revises: 0183b6461709
Create Date: 2022-03-10 13:47:06.799865

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "deca299cc7f2"
down_revision = "0183b6461709"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "rm_gbl_contractor_project_history_bsl",
        sa.Column("tenant_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
    )
    op.add_column(
        "rm_gbl_contractor_project_history_bsl_stddev",
        sa.Column("tenant_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("rm_gbl_contractor_project_history_bsl_stddev", "tenant_id")
    op.drop_column("rm_gbl_contractor_project_history_bsl", "tenant_id")
    # ### end Alembic commands ###
