"""update project location total task risk model

Revision ID: ded676bb7be8
Revises: 7f40094f46b5
Create Date: 2022-02-04 19:03:20.957270

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "ded676bb7be8"
down_revision = "7f40094f46b5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rm_project_total_task_risk_score",
        sa.Column("calculated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("tenant", sqlmodel.sql.sqltypes.GUID(), nullable=True),
        sa.Column("project_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("calculated_at"),
    )
    op.create_table(
        "rm_project_location_total_task_risk_score",
        sa.Column("calculated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("tenant", sqlmodel.sql.sqltypes.GUID(), nullable=True),
        sa.Column("project_location_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_location_id"],
            ["project_locations.id"],
        ),
        sa.PrimaryKeyConstraint("calculated_at"),
    )
    op.drop_table("rm_total_task_risk_score")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rm_total_task_risk_score",
        sa.Column(
            "calculated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "value",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("tenant", postgresql.UUID(), autoincrement=False, nullable=True),
        sa.Column("project_id", postgresql.UUID(), autoincrement=False, nullable=False),
        sa.Column("date", sa.DATE(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name="rm_total_task_risk_score_project_id_fkey",
        ),
        sa.PrimaryKeyConstraint("calculated_at", name="rm_total_task_risk_score_pkey"),
    )
    op.drop_table("rm_project_location_total_task_risk_score")
    op.drop_table("rm_project_total_task_risk_score")
    # ### end Alembic commands ###
