"""Create StochasticTotalWorkPackageRiskScoreModel Table

Revision ID: e388c46da969
Revises: 4b9d3ddd0cb2
Create Date: 2022-10-11 16:54:55.358339

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "e388c46da969"
down_revision = "4b9d3ddd0cb2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rm_stochastic_total_work_package_risk_score",
        sa.Column("calculated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("inputs", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("project_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("calculated_at", "project_id"),
    )
    op.create_index(
        "rm_stochastic_total_work_package_risk_score_entity_idx",
        "rm_stochastic_total_work_package_risk_score",
        ["project_id", "date"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "rm_stochastic_total_work_package_risk_score_entity_idx",
        table_name="rm_stochastic_total_work_package_risk_score",
    )
    op.drop_table("rm_stochastic_total_work_package_risk_score")
    # ### end Alembic commands ###
