"""create contractor safety score table and add tenant as field

Revision ID: ecd2d6dacb9b
Revises: 64d4da7c96a5
Create Date: 2022-01-20 11:52:16.113069

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "ecd2d6dacb9b"
down_revision = "64d4da7c96a5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rm_contractor_safety_score",
        sa.Column("calculated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("tenant", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("calculated_at"),
    )
    op.add_column(
        "rm_contractor_safety_history",
        sa.Column("tenant", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "rm_gbl_contractor_project_history_bsl",
        sa.Column("tenant", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "rm_gbl_contractor_project_history_bsl_stddev",
        sa.Column("tenant", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("rm_gbl_contractor_project_history_bsl_stddev", "tenant")
    op.drop_column("rm_gbl_contractor_project_history_bsl", "tenant")
    op.drop_column("rm_contractor_safety_history", "tenant")
    op.drop_table("rm_contractor_safety_score")
    # ### end Alembic commands ###
