"""setting up supervisor engagement factor

Revision ID: f060338b1b31
Revises: 78ce7f572b97
Create Date: 2022-01-27 12:01:59.608051

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "f060338b1b31"
down_revision = "78ce7f572b97"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rm_supervisor_engagement_factor",
        sa.Column("calculated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("tenant", sqlmodel.sql.sqltypes.GUID(), nullable=True),
        sa.Column("supervisor_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.PrimaryKeyConstraint("calculated_at", "supervisor_id"),
    )
    op.execute(
        """
        INSERT INTO rm_calc_parameters (name, value) VALUES
        ('sef_obs_number_threshold', '4'),
        ('sef_esd_number_threshold', '4'),
        ('sef_obs_number_value_below', '1'),
        ('sef_obs_number_value_above', '0'),
        ('sef_esd_number_value_below', '1'),
        ('sef_esd_number_value_above', '0'),
        ('sef_obs_timing_threshold_first', '0.25'),
        ('sef_obs_timing_threshold_second', '0.5'),
        ('sef_obs_timing_threshold_third', '0.75'),
        ('sef_obs_timing_value_first', '0'),
        ('sef_obs_timing_value_second', '1'),
        ('sef_obs_timing_value_third', '1.5'),
        ('sef_obs_timing_value_fourth', '2'),
        ('sef_esd_timing_threshold_first', '0.25'),
        ('sef_esd_timing_threshold_second', '0.5'),
        ('sef_esd_timing_threshold_third', '0.75'),
        ('sef_esd_timing_value_first', '0'),
        ('sef_esd_timing_value_second', '1'),
        ('sef_esd_timing_value_third', '1.5'),
        ('sef_esd_timing_value_fourth', '2'),
        ('sef_obs_month_fraction', '0.75'),
        ('sef_esd_month_fraction', '0.75');
        """
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("rm_supervisor_engagement_factor")

    op.execute(
        """
        DELETE FROM rm_calc_parameters WHERE name in (
            'sef_obs_number_threshold',
            'sef_esd_number_threshold',
            'sef_obs_number_value_below',
            'sef_obs_number_value_above',
            'sef_esd_number_value_below',
            'sef_esd_number_value_above',
            'sef_obs_timing_threshold_first',
            'sef_obs_timing_threshold_second',
            'sef_obs_timing_threshold_third',
            'sef_obs_timing_value_first',
            'sef_obs_timing_value_second',
            'sef_obs_timing_value_third',
            'sef_obs_timing_value_fourth',
            'sef_esd_timing_threshold_first',
            'sef_esd_timing_threshold_second',
            'sef_esd_timing_threshold_third',
            'sef_esd_timing_value_first',
            'sef_esd_timing_value_second',
            'sef_esd_timing_value_third',
            'sef_esd_timing_value_fourth',
            'sef_obs_month_fraction',
            'sef_esd_month_fraction'
        );
        """
    )
    # ### end Alembic commands ###
