"""Foreign keys indexes

Revision ID: f264f41cb18b
Revises: e47146dcdd71
Create Date: 2022-11-18 17:02:32.574476

"""
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "f264f41cb18b"
down_revision = "e47146dcdd71"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("activities_crew_id_ix", "activities", ["crew_id"], unique=False)
    op.create_index(
        "activities_library_activity_type_id_ix",
        "activities",
        ["library_activity_type_id"],
        unique=False,
    )
    op.create_index(
        "activities_location_id_ix", "activities", ["location_id"], unique=False
    )
    op.create_index(
        "contractor_tenant_id_ix", "contractor", ["tenant_id"], unique=False
    )
    op.create_index(
        "contractor_aliases_contractor_id_ix",
        "contractor_aliases",
        ["contractor_id"],
        unique=False,
    )
    op.create_index(
        "contractor_aliases_tenant_id_ix",
        "contractor_aliases",
        ["tenant_id"],
        unique=False,
    )
    op.create_index(
        "daily_reports_completed_by_id_ix",
        "daily_reports",
        ["completed_by_id"],
        unique=False,
    )
    op.create_index(
        "daily_reports_created_by_id_ix",
        "daily_reports",
        ["created_by_id"],
        unique=False,
    )
    op.create_index(
        "incidents_contractor_id_ix", "incidents", ["contractor_id"], unique=False
    )
    op.create_index(
        "incidents_supervisor_id_ix", "incidents", ["supervisor_id"], unique=False
    )
    op.create_index("incidents_tenant_id_ix", "incidents", ["tenant_id"], unique=False)
    op.create_index(
        "ingest_work_package_to_compatible_unit_link_tenant_id_ix",
        "ingest_work_package_to_compatible_unit_link",
        ["tenant_id"],
        unique=False,
    )
    op.create_index(
        "library_tasks_work_type_id_ix", "library_tasks", ["work_type_id"], unique=False
    )
    op.create_index(
        "observations_contractor_involved_id_ix",
        "observations",
        ["contractor_involved_id"],
        unique=False,
    )
    op.create_index(
        "observations_supervisor_id_ix", "observations", ["supervisor_id"], unique=False
    )
    op.create_index(
        "observations_tenant_id_ix", "observations", ["tenant_id"], unique=False
    )
    op.create_index(
        "parsed_files_tenant_id_ix", "parsed_files", ["tenant_id"], unique=False
    )
    op.create_index(
        "locations_project_id_ix", "project_locations", ["project_id"], unique=False
    )
    op.create_index(
        "locations_supervisor_id_ix",
        "project_locations",
        ["supervisor_id"],
        unique=False,
    )
    op.create_index(
        "work_packages_contractor_id_ix", "projects", ["contractor_id"], unique=False
    )
    op.create_index(
        "work_packages_library_asset_type_id_ix",
        "projects",
        ["library_asset_type_id"],
        unique=False,
    )
    op.create_index(
        "work_packages_library_division_id_ix",
        "projects",
        ["library_division_id"],
        unique=False,
    )
    op.create_index(
        "work_packages_library_project_type_id_ix",
        "projects",
        ["library_project_type_id"],
        unique=False,
    )
    op.create_index(
        "work_packages_library_region_id_ix",
        "projects",
        ["library_region_id"],
        unique=False,
    )
    op.create_index(
        "work_packages_manager_id_ix", "projects", ["manager_id"], unique=False
    )
    op.create_index(
        "work_packages_primary_assigned_user_id_ix",
        "projects",
        ["supervisor_id"],
        unique=False,
    )
    op.create_index(
        "site_condition_controls_library_control_id_ix",
        "site_condition_controls",
        ["library_control_id"],
        unique=False,
    )
    op.create_index(
        "site_condition_controls_site_condition_hazard_id_ix",
        "site_condition_controls",
        ["site_condition_hazard_id"],
        unique=False,
    )
    op.create_index(
        "site_condition_hazards_library_hazard_id_ix",
        "site_condition_hazards",
        ["library_hazard_id"],
        unique=False,
    )
    op.create_index(
        "site_condition_hazards_site_condition_id_ix",
        "site_condition_hazards",
        ["site_condition_id"],
        unique=False,
    )
    op.create_index(
        "supervisor_tenant_id_ix", "supervisor", ["tenant_id"], unique=False
    )
    op.create_index(
        "task_controls_library_control_id_ix",
        "task_controls",
        ["library_control_id"],
        unique=False,
    )
    op.create_index(
        "task_controls_task_hazard_id_ix",
        "task_controls",
        ["task_hazard_id"],
        unique=False,
    )
    op.create_index(
        "tasks_hazards_library_hazard_id_ix",
        "task_hazards",
        ["library_hazard_id"],
        unique=False,
    )
    op.create_index("tasks_activity_id_ix", "tasks", ["activity_id"], unique=False)


def downgrade():
    op.drop_index("tasks_activity_id_ix", table_name="tasks")
    op.drop_index("tasks_hazards_library_hazard_id_ix", table_name="task_hazards")
    op.drop_index("task_controls_task_hazard_id_ix", table_name="task_controls")
    op.drop_index("task_controls_library_control_id_ix", table_name="task_controls")
    op.drop_index("supervisor_tenant_id_ix", table_name="supervisor")
    op.drop_index(
        "site_condition_hazards_site_condition_id_ix",
        table_name="site_condition_hazards",
    )
    op.drop_index(
        "site_condition_hazards_library_hazard_id_ix",
        table_name="site_condition_hazards",
    )
    op.drop_index(
        "site_condition_controls_site_condition_hazard_id_ix",
        table_name="site_condition_controls",
    )
    op.drop_index(
        "site_condition_controls_library_control_id_ix",
        table_name="site_condition_controls",
    )
    op.drop_index("work_packages_primary_assigned_user_id_ix", table_name="projects")
    op.drop_index("work_packages_manager_id_ix", table_name="projects")
    op.drop_index("work_packages_library_region_id_ix", table_name="projects")
    op.drop_index("work_packages_library_project_type_id_ix", table_name="projects")
    op.drop_index("work_packages_library_division_id_ix", table_name="projects")
    op.drop_index("work_packages_library_asset_type_id_ix", table_name="projects")
    op.drop_index("work_packages_contractor_id_ix", table_name="projects")
    op.drop_index("locations_supervisor_id_ix", table_name="project_locations")
    op.drop_index("locations_project_id_ix", table_name="project_locations")
    op.drop_index("parsed_files_tenant_id_ix", table_name="parsed_files")
    op.drop_index("observations_tenant_id_ix", table_name="observations")
    op.drop_index("observations_supervisor_id_ix", table_name="observations")
    op.drop_index("observations_contractor_involved_id_ix", table_name="observations")
    op.drop_index("library_tasks_work_type_id_ix", table_name="library_tasks")
    op.alter_column(
        "ingestion_process",
        "submitted_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.drop_index(
        "ingest_work_package_to_compatible_unit_link_tenant_id_ix",
        table_name="ingest_work_package_to_compatible_unit_link",
    )
    op.drop_index("incidents_tenant_id_ix", table_name="incidents")
    op.drop_index("incidents_supervisor_id_ix", table_name="incidents")
    op.drop_index("incidents_contractor_id_ix", table_name="incidents")
    op.drop_index("daily_reports_created_by_id_ix", table_name="daily_reports")
    op.drop_index("daily_reports_completed_by_id_ix", table_name="daily_reports")
    op.drop_index("contractor_aliases_tenant_id_ix", table_name="contractor_aliases")
    op.drop_index(
        "contractor_aliases_contractor_id_ix", table_name="contractor_aliases"
    )
    op.drop_index("contractor_tenant_id_ix", table_name="contractor")
    op.drop_index("activities_location_id_ix", table_name="activities")
    op.drop_index("activities_library_activity_type_id_ix", table_name="activities")
    op.drop_index("activities_crew_id_ix", table_name="activities")
