"""Add Project Location Lat Long

Revision ID: fe793e1e0461
Revises: c703c8abd734
Create Date: 2021-12-10 10:54:43.096482

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "fe793e1e0461"
down_revision = "c703c8abd734"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project_locations",
        sa.Column("latitude", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.add_column(
        "project_locations",
        sa.Column("longitude", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.create_index(
        op.f("ix_project_locations_latitude"),
        "project_locations",
        ["latitude"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_locations_longitude"),
        "project_locations",
        ["longitude"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_project_locations_longitude"), table_name="project_locations"
    )
    op.drop_index(op.f("ix_project_locations_latitude"), table_name="project_locations")
    op.drop_column("project_locations", "longitude")
    op.drop_column("project_locations", "latitude")
    # ### end Alembic commands ###
