import type { Tenant } from "@/types/tenant/Tenant";

const insightsTenant: Tenant = {
  name: "urbint",
  displayName: "Urbint",
  entities: [
    {
      key: "workPackage",
      label: "Work Package",
      labelPlural: "Work Packages",
      defaultLabel: "Work Package",
      defaultLabelPlural: "Work Packages",
      attributes: [
        {
          key: "name",
          label: "Project Name",
          labelPlural: "Project Names",
          defaultLabel: "Work Package Name",
          defaultLabelPlural: "Work Package Names",
          mandatory: true,
          visible: true,
          required: true,
          filterable: true,
          mappings: null,
        },
        {
          key: "status",
          label: "Project Status",
          labelPlural: "Project Statuses",
          defaultLabel: "Status",
          defaultLabelPlural: "Statuses",
          mandatory: true,
          visible: true,
          required: true,
          filterable: false,
          mappings: {
            pending: ["Pending"],
            active: ["Active"],
            completed: ["Completed"],
          },
        },
        {
          key: "externalKey",
          label: "Project Number",
          labelPlural: "Project Numbers",
          defaultLabel: "External key",
          defaultLabelPlural: "External keys",
          mandatory: true,
          visible: true,
          required: true,
          filterable: true,
          mappings: null,
        },
        {
          key: "startDate",
          label: "Start date",
          labelPlural: "Start dates",
          defaultLabel: "Start date",
          defaultLabelPlural: "Start dates",
          mandatory: true,
          visible: true,
          required: true,
          filterable: true,
          mappings: null,
        },
        {
          key: "endDate",
          label: "End date",
          labelPlural: "End dates",
          defaultLabel: "End date",
          defaultLabelPlural: "End dates",
          mandatory: true,
          visible: true,
          required: true,
          filterable: true,
          mappings: null,
        },
        {
          key: "region",
          label: "Region",
          labelPlural: "Regions",
          defaultLabel: "Region",
          defaultLabelPlural: "Regions",
          mandatory: true,
          visible: true,
          required: true,
          filterable: true,
          mappings: null,
        },
        {
          key: "division",
          label: "Division",
          labelPlural: "Divisions",
          defaultLabel: "Division",
          defaultLabelPlural: "Divisions",
          mandatory: true,
          visible: true,
          required: true,
          filterable: true,
          mappings: null,
        },
        {
          key: "primeContractor",
          label: "Prime contractor",
          labelPlural: "Prime contractors",
          defaultLabel: "Prime contractor",
          defaultLabelPlural: "Prime contractors",
          mandatory: true,
          visible: true,
          required: true,
          filterable: true,
          mappings: null,
        },
      ],
    },
    {
      key: "location",
      label: "Location",
      labelPlural: "Locations",
      defaultLabel: "Location",
      defaultLabelPlural: "Locations",
      attributes: [
        {
          key: "name",
          label: "Location Name",
          labelPlural: "Location Names",
          defaultLabel: "Location Name",
          defaultLabelPlural: "Location Names",
          mandatory: true,
          visible: true,
          required: true,
          filterable: true,
          mappings: null,
        },
      ],
    },
    {
      key: "activity",
      label: "Activity",
      labelPlural: "Activities",
      defaultLabel: "Activity",
      defaultLabelPlural: "Activities",
      attributes: [],
    },
    {
      key: "task",
      label: "Task",
      labelPlural: "Tasks",
      defaultLabel: "Task",
      defaultLabelPlural: "Tasks",
      attributes: [],
    },
    {
      key: "hazard",
      label: "Hazard",
      labelPlural: "Hazards",
      defaultLabel: "Hazard",
      defaultLabelPlural: "Hazards",
      attributes: [],
    },
    {
      key: "control",
      label: "Control",
      labelPlural: "Controls",
      defaultLabel: "Control",
      defaultLabelPlural: "Controls",
      attributes: [],
    },
    {
      key: "templateForm",
      label: "Template Form",
      labelPlural: "templateForms",
      defaultLabel: "Template Form",
      defaultLabelPlural: "Template Forms",
      attributes: [],
    },
    
  ],
  workos: [],
};

const customInsightsTenant: Tenant = {
  ...insightsTenant,
  entities: [
    {
      key: "workPackage",
      label: "My Work Package",
      labelPlural: "My Work Packages",
      defaultLabel: "Work Package",
      defaultLabelPlural: "Work Packages",
      attributes: [
        {
          key: "primeContractor",
          label: "My Work Package Prime Contractor",
          labelPlural: "My Work Package Prime Contractors",
          defaultLabel: "Prime contractor",
          defaultLabelPlural: "Prime contractors",
          mandatory: true,
          visible: true,
          required: true,
          filterable: true,
          mappings: null,
        },
        {
          key: "division",
          label: "My Work Package Division",
          labelPlural: "My Work Package Divisions",
          defaultLabel: "division",
          defaultLabelPlural: "divisions",
          mandatory: true,
          visible: true,
          required: true,
          filterable: true,
          mappings: null,
        },
        {
          key: "region",
          label: "My Work Package Region",
          labelPlural: "My Work Package Regions",
          defaultLabel: "region",
          defaultLabelPlural: "regions",
          mandatory: true,
          visible: true,
          required: true,
          filterable: true,
          mappings: null,
        },
        {
          key: "status",
          label: "My Work Package Status",
          labelPlural: "My Work Package Statuses",
          defaultLabel: "status",
          defaultLabelPlural: "statuses",
          mandatory: true,
          visible: true,
          required: true,
          filterable: true,
          mappings: null,
        },
        {
          key: "name",
          label: "My Work Package Name",
          labelPlural: "My Work Package Names",
          defaultLabel: "Work Package Name",
          defaultLabelPlural: "Work Package Names",
          mandatory: true,
          visible: true,
          required: true,
          filterable: true,
          mappings: null,
        },
        {
          key: "externalKey",
          label: "My Work Package Number",
          labelPlural: "My Work Package Numbers",
          defaultLabel: "External key",
          defaultLabelPlural: "External keys",
          mandatory: true,
          visible: true,
          required: true,
          filterable: true,
          mappings: null,
        },
        {
          key: "startDate",
          label: "My Work Package Start Date",
          labelPlural: "My Work Package Start Dates",
          defaultLabel: "Start date",
          defaultLabelPlural: "Start dates",
          mandatory: true,
          visible: true,
          required: true,
          filterable: true,
          mappings: null,
        },
        {
          key: "endDate",
          label: "My Work Package End Date",
          labelPlural: "My Work Package End Dates",
          defaultLabel: "End date",
          defaultLabelPlural: "End dates",
          mandatory: true,
          visible: true,
          required: true,
          filterable: true,
          mappings: null,
        },
      ],
    },
    {
      key: "location",
      label: "My Location",
      labelPlural: "My Locations",
      defaultLabel: "Location",
      defaultLabelPlural: "Locations",
      attributes: [],
    },
  ],
};

export { insightsTenant, customInsightsTenant };
