fragment Recommendations on Recommendation {
  dailyReport(projectLocationId: $projectLocationsId) {
    crew {
      constructionCompany
      foremanName
    }
    safetyAndCompliance {
      phaCompletion
      sopNumber
      sopType
      stepsCalledIn
    }
  }
}
