query PortfolioLearningsProjectRiskCount($filters: PortfolioLearningsInput!) {
  portfolioLearnings(portfolioLearningsInput: $filters) {
    projectRiskLevelOverTime {
      date
      riskLevel
      count
    }
  }
}
