query PortfolioPlanningProjectRiskCount($filters: PortfolioPlanningInput!) {
  portfolioPlanning(portfolioPlanningInput: $filters) {
    projectRiskLevelOverTime {
      date
      riskLevel
      count
    }
  }
}
