query PortfolioLearningsControlsNotImplemented(
  $filters: PortfolioLearningsInput!
) {
  portfolioLearnings(portfolioLearningsInput: $filters) {
    notImplementedControls {
      percent
      libraryControl {
        id
        name
      }
    }
  }
}
