query PortfolioLearningsReasonsNotImplementedCount(
  $filters: PortfolioLearningsInput!
) {
  portfolioLearnings(portfolioLearningsInput: $filters) {
    reasonsControlsNotImplemented {
      count
      reason
    }
  }
}
