query PortfolioPlanningTaskRiskLevelByDate(
  $filters: PortfolioPlanningInput!
  $taskOrderBy: [TaskOrderBy!]
) {
  portfolioPlanning(portfolioPlanningInput: $filters) {
    taskRiskLevelByDate(orderBy: $taskOrderBy) {
      taskName
      projectName
      riskLevelByDate {
        date
        riskLevel
      }
    }
  }
}
