query PortfolioLearningsApplicableHazards($filters: PortfolioLearningsInput!) {
  portfolioLearnings(portfolioLearningsInput: $filters) {
    applicableHazards {
      count
      libraryHazard {
        id
        name
      }
    }
  }
}
