query PortfolioPlanningProjectRiskLevelByDate(
  $filters: PortfolioPlanningInput!
) {
  portfolioPlanning(portfolioPlanningInput: $filters) {
    projectRiskLevelByDate {
      projectName
      riskLevelByDate {
        date
        riskLevel
      }
    }
  }
}
