query ProjectLearningsControlsNotImplemented($filters: ProjectLearningsInput!) {
  projectLearnings(projectLearningsInput: $filters) {
    notImplementedControls {
      percent
      libraryControl {
        id
        name
      }
    }
  }
}
