query ProjectPlanningLocationRiskCount($filters: ProjectPlanningInput!) {
  projectPlanning(projectPlanningInput: $filters) {
    locationRiskLevelOverTime {
      date
      riskLevel
      count
    }
  }
}
