query ProjectPlanningLocationRiskLevelByDate($filters: ProjectPlanningInput!) {
  projectPlanning(projectPlanningInput: $filters) {
    locationRiskLevelByDate {
      locationName
      riskLevelByDate {
        date
        riskLevel
      }
    }
  }
}
