query ProjectLearningsLocationRiskCount($filters: ProjectLearningsInput!) {
  projectLearnings(projectLearningsInput: $filters) {
    locationRiskLevelOverTime {
      date
      riskLevel
      count
    }
  }
}
