query ProjectLearningsApplicableHazards($filters: ProjectLearningsInput!) {
  projectLearnings(projectLearningsInput: $filters) {
    applicableHazards {
      count
      libraryHazard {
        id
        name
      }
    }
  }
}
