query ProjectLearningsReasonsNotImplementedCount(
  $filters: ProjectLearningsInput!
) {
  projectLearnings(projectLearningsInput: $filters) {
    reasonsControlsNotImplemented {
      count
      reason
    }
  }
}
