export const distributionBulletins = [
  "DB_8-01 - Inspection Of Padmounted And Above Ground Equipment",
  "DB_8-02 - Underground Distribution Installation And Operating Practices",
  "DB_8-03 - Underground Distribution Guidelines",
  "DB_8-04 - Testing and Maintenance of Primary Voltage Underground Cables",
  "DB_8-05 - Utilities Protection Act",
  "DB_8-07 - Safe Practices for Making Excavations",
  "DB_8-08 - Installation and Emergency Replacement of 46kV Pole Mounted & Pad-mounted Transmission Class and Distribution Class Transformer",
  "DB_8-09 - Underground Cable Locating",
  "DB_8-11 - Internal Inspection and Repair of Padmounted Switchgear",
  "DB_9-01 - Fall Protection Equipment Care And Inspection Guidelines",
  "DB_9-02 - Installation And Inspection Of Fire Extinguishers On Vehicles",
  "DB_9-03 - Field Care And Maintenance Of Fiberglass Hotsticks",
  "DB_9-04 - Testing And Refinishing Of Fiberglass Reinforced Plastic (Frp) Rod And Tube Used In Live Line Tools (Sticks)",
  "DB_9-05 - Insulated Rubber Goods Testing And Care",
  "DB_9-07 - Safe Operating Practices For Insulated Aerial Devices",
  "DB_9-08 - Personal Protective Grounding / Work Practices",
  "DB_9-09 - Insulation Tests For Insulated Aerial Devices",
  "DB_9-10 - Safety Requirements For Crane Operation",
  "DB_9-11 - Truck And Equipment Retrieval",
  "DB_9-12 - Operation Of Powered Industrial Trucks (Forklifts)",
  "DB_9-13 - Truck And Equipment Grounding",
  "DB_9-14 - Minimum Approach Distances",
  "DB_9-15 - Safe Chocking Practices For Dual Wheel, Heavy Vehicles And Trailers.",
  "DB_9-16 - Application And Use Of Winch Lines In Distribution Operations",
  "DB_9-17 - Care And Use Of Air And Hydraulic Hoses",
  "DB_9-18 - Dielectric Test For Air And Hydraulic Nonconductive Hoses",
  "DB_9-19 - Installing And Removing Poles In Energized Distribution Lines - Safe Operating Practices",
  "DB_9-20 - Safe Work Practices For Enclosed Spaces",
  "DB_9-21 - Safety, Operation And Field Maintenance Of Motorized Trenching Equipment",
  "DB_9-22 - Safe Work Practices For Confined Spaces",
  "DB_9-23 - Personal Protective Equipment Basic Requirements For Distribution Organization",
  "DB_9-24 - Written Job Briefing",
  "DB_9-25 - Hauling Poles On Line Trucks Equipped With Pole Brack",
  "DB_9-26 - Distribution Regulator Switching",
  "DB_9-27 - Spacer Cable Operation And Maintenance Procedure",
  "DB_9-28 - Synthetic/Wire Rope Inspection For Distribution Pullers/Tensioners",
  "DB_9-29 - Hoisted Loads Drop Zone Safety",
  "DB_1-01 - Distribution Work Order Approval",
  "DB_1-02 - Distribution Work Order Preparation & Completion Procedures",
  "DB_1-03 - Physical Data Defintions",
  "DB_1-04 - Blanket Work Orders",
  "DB_1-05 - Repair Allowance",
  "DB_1-06 - Distribution Financial Policies",
  "DB_2-01 - Conversion Of Transmission To Distribution Or Distribution To Transmission",
  "DB_2-04 - Service To Billboards",
  "DB_2-05 - Sale Or Purchase Of Distribution Facilities",
  "DB_2-06 - Depreciation Table For Distribution Facilities",
  "DB_3-01 - Residential Wiring Plan",
  "DB_3-03 - Watthour Meters: Disconnecting And Removing",
  "DB_3-08 - Supplying Metering Pulses To Customers",
  "DB_3-09 - Electric Service Inspections",
  "DB_3-11 - Meter Order Procedures",
  "DB_3-13 - Field Testing Meters For High Bill Inquiries",
  "DB_3-27 - Sharing Of Metering Potential In Substations",
  "DB_4-06 - Distribution Reclosure Maintenance",
  "DB_4-07 - Customer Request For System Information (Arc Flash Calculation)",
  "DB_4-08 - Maintenance of Distribution Automatic Throwover Switches",
  "DB_4-09 - Distribution Cutouts",
  "DB_4-11 - Motor Start Information",
  "DB_4-12 - Fault Indicator Guidelines",
  "DB_5-01 - Open-Delta Secondary Transformer Bank",
  "DB_5-02 - Standard Voltages And Transformers",
  "DB_5-03 - Distribution Transformer Venting",
  "DB_5-04 - Reuse Of Distribution Transformers",
  "DB_5-05 - Pole Mounted Distribution Capacitors",
  "DB_6-01 - Distribution Tree Conductor",
  "DB_6-04 - Line Post Insulators And Suspension Insulators",
  "DB_6-05 - Groundline Inspection And Treatment Of Wood Poles",
  "DB_7-01 - Outdoor Lighting Service",
  "DB_7-02 - Traffic Control Systems",
  "DB_7-04 - Outdoor Light Conversions",
  "DB_7-06 - Underground Street Lighting Conductor",
  "DB_10-01 - Pole Attachment Rental Procedure",
  "DB_10-04 - Joint Use Of Distribution Poles With Telephone Companies, Telecommunications Companies, Catv Companies, Emcs, Municipal Power Providers, Governmental Entities, And Others",
  "DB_10-05 - Joint Trenching",
  "DB_10-08 - Inspection Of Overhead Distribution Facilities",
  "DB_11-01 - Pole Locations On Dot Projects",
  "DB_11-02 - Work Area Traffic Control And Warning Devices",
  "DB_12-02 - Customer Owned Right-Of-Way Crossings",
  "DB_12-03 - Right Of Way Danger Tree Removal Work Process",
  "DB_12-05 - Transmission And Distribution Line Underbuild And Row Crossings",
  "DB_13-02 - Overhead Line Hazards To Air Navigation",
  "DB_13-03 - Notice Of Intent And Notice Of Termination Storm Water Discharge Permits",
  "DB_13-19 - Georgia Power Company Policy Regarding External Permit Applications",
  "DB_18-04 - Emergency Operations And Procedures",
  "DB_18-05 - Instructions For Reporting Major System Disturbances",
  "DB_18-07 - Application Of Distribution Automation Devices",
  "DB_18-09 - Selection And Payment Of Distribution Contractors",
  "DB_18-10 - High Voltage Safety Act Official Code Of Georgia Annotated Sections 46-3-30 Through 46-3-40",
  "DB_18-11 - Customer Request To Cover Conductors 750 Volts Or Less",
  "DB_18-13 - Clearances For Power Lines Over Waterways And Waterbodies",
  "DB_18-16 - Stray Voltage (Nev)",
  "DB_18-17 - Installation Of An Optional Standby System(Backup) Generator",
  "DB_18-18 - Distribution Planning",
  "DB_18-19 - Electric Service Across State Lines",
  "DB_18-20 - Colors For Marking Device Status On Switching Maps",
  "DB_18-21 - Land Sale Process",
  "DB_18-23 - Interconnection Requirements For Non-Exporting Generators",
  "DB_18-24 - Customer Source Selection Requirements",
  "DB_18-25 - Energized Work Permit With Distributed Generation",
];
