query LastAddedAdhocJobSafetyBriefing {
  lastAddedAdhocJobSafetyBriefing
   {
    contents {
      workLocation {
        address
        operatingHq
      }
      nearestMedicalFacility {
        address
        description
        city
        distanceFromJob
        phoneNumber
        state
        zip
      }
      aedInformation {
        location
      }
      emergencyContacts {
        name
        phoneNumber
        primary
      }
    }
  }
}
