"""updated insight table unique constraint

Revision ID: 1c6650ce09c7
Revises: 9cd8c877e870
Create Date: 2023-11-02 20:01:49.776381

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "1c6650ce09c7"
down_revision = "9cd8c877e870"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TABLE insight DROP CONSTRAINT IF EXISTS insight_name_tenant_id_uix"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "insight_name_tenant_id_uix", "insight", ["tenant_id", "name"]
    )
    # ### end Alembic commands ###
