"""Update model LibraryHazard

Revision ID: 2231a4120b92
Revises: 71a50b752e41
Create Date: 2025-07-07 15:51:45.046039

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2231a4120b92"
down_revision = "71a50b752e41"
branch_labels = None
depends_on = None

gcs_urls = [
    "https://storage.googleapis.com/worker-safety-public-icons/png-icons/ArchFlash.png",
    "https://storage.googleapis.com/worker-safety-public-icons/png-icons/Chemical.png",
    "https://storage.googleapis.com/worker-safety-public-icons/png-icons/DefaultHazardIcon.png",
    "https://storage.googleapis.com/worker-safety-public-icons/png-icons/ElectricContactWithSource.png",
    "https://storage.googleapis.com/worker-safety-public-icons/png-icons/ExcavationOfTrench.png",
    "https://storage.googleapis.com/worker-safety-public-icons/png-icons/FallFromElevation.png",
    "https://storage.googleapis.com/worker-safety-public-icons/png-icons/Fire.png",
    "https://storage.googleapis.com/worker-safety-public-icons/png-icons/FireWithSustainedFuelSource.png",
    "https://storage.googleapis.com/worker-safety-public-icons/png-icons/HeavyRotatingEquipment.png",
    "https://storage.googleapis.com/worker-safety-public-icons/png-icons/HighDoseOfToxicChemicalOrRadiation.png",
    "https://storage.googleapis.com/worker-safety-public-icons/png-icons/HighTemperature.png",
    "https://storage.googleapis.com/worker-safety-public-icons/png-icons/LossofControlofSuspendedLoads.png",
    "https://storage.googleapis.com/worker-safety-public-icons/png-icons/MobileEquipmentAndWorkersOnFoot.png",
    "https://storage.googleapis.com/worker-safety-public-icons/png-icons/MotionMobileEquipment.png",
    "https://storage.googleapis.com/worker-safety-public-icons/png-icons/MotorVehicleIncident.png",
    "https://storage.googleapis.com/worker-safety-public-icons/png-icons/Steam.png",
    "https://storage.googleapis.com/worker-safety-public-icons/png-icons/SuspendedLoad.png",
    "https://storage.googleapis.com/worker-safety-public-icons/png-icons/Vector%2035-Explosion.png",
    "https://storage.googleapis.com/worker-safety-public-icons/png-icons/other.png",
]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "library_hazards",
        sa.Column(
            "image_url_png",
            sa.String(),
            nullable=False,
            server_default="https://storage.googleapis.com/worker-safety-public-icons/png-icons/DefaultHazardIcon.png",
        ),
    )

    # Dictionary to store mapping from original_image_url to new_png_url
    url_mappings = {}

    for png_url in gcs_urls:
        # Derive the SVG URL by replacing .png with .svg
        # Note: This assumes a direct 1:1 mapping and consistent naming.
        svg_url = png_url.replace(".png", ".svg")

        # Derive the 'image_url' that would be in the database
        original_image_url_for_db_match = svg_url.replace("/png-icons/", "/")
        url_mappings[original_image_url_for_db_match] = png_url

    bind = op.get_bind()

    for original_svg_url, png_url in url_mappings.items():
        try:
            # Construct the update statement using bind.execute()
            # Parameters are passed directly to execute
            update_stmt = sa.text(
                "UPDATE library_hazards SET image_url_png = :png_url WHERE image_url = :original_svg_url"
            )
            bind.execute(
                update_stmt, {"png_url": png_url, "original_svg_url": original_svg_url}
            )
        except Exception as e:
            # In Alembic, op.execute() or bind.execute() within upgrade() are typically
            # part of a single transaction. If an error occurs, the entire migration
            # might be rolled back by Alembic's transaction management.
            # Printing the error is still useful for debugging.
            print(f"Error updating DB for {original_svg_url}: {e}")
            # No explicit rollback needed here as Alembic handles the transaction.

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("library_hazards", "image_url_png")
    # ### end Alembic commands ###
