"""added last token generated at field in user

Revision ID: 2bc5bd1bf87f
Revises: ff29dc0c207d
Create Date: 2024-05-14 17:18:48.485254

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2bc5bd1bf87f"
down_revision = "ff29dc0c207d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("last_token_generated_at", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "last_token_generated_at")
    # ### end Alembic commands ###
