"""Add LibraryTaskLibraryHazardLink table

Revision ID: 3f5c709d7117
Revises: 78460a6f00a4
Create Date: 2023-09-28 14:03:36.560404

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

from worker_safety_service.models.utils import EnumValues

# revision identifiers, used by Alembic.
revision = "3f5c709d7117"
down_revision = "78460a6f00a4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "library_task_library_hazard_link",
        sa.Column(
            "applicability_level",
            EnumValues(
                "always", "mostly", "rarely", "never", name="applicabilitylevel"
            ),
            nullable=False,
        ),
        sa.Column("library_task_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("library_hazard_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["library_hazard_id"],
            ["library_hazards.id"],
        ),
        sa.ForeignKeyConstraint(
            ["library_task_id"],
            ["library_tasks.id"],
        ),
        sa.PrimaryKeyConstraint("library_task_id", "library_hazard_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("library_task_library_hazard_link")
    # ### end Alembic commands ###
