"""Add work_type code

Revision ID: 6526beee5559
Revises: c02d231568ca
Create Date: 2025-05-21 16:47:32.354420

"""
import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision = "6526beee5559"
down_revision = "c02d231568ca"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "work_types",
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.create_unique_constraint("work_types_unique_field_code", "work_types", ["code"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("work_types_unique_field_code", "work_types", type_="unique")
    op.drop_column("work_types", "code")
    # ### end Alembic commands ###
