"""Remove unique constraint from work_types code

Revision ID: 6b997b939778
Revises: c797b2d45579
Create Date: 2024-03-26 10:00:00.000000

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "6b997b939778"
down_revision = "ac43ac9c07b3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("work_types_unique_field_code", "work_types", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("work_types_unique_field_code", "work_types", ["code"])
    # ### end Alembic commands ###
