"""Add work_type code for ng tenant

Revision ID: 7fb47f093f1a
Revises: 6b997b939778
Create Date: 2025-05-29 16:58:15.555937

"""
import uuid

from alembic import op
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision = "7fb47f093f1a"
down_revision = "6b997b939778"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()

    # Find the ng and test-ng tenant IDs
    ng_tenants = conn.execute(
        text("SELECT id FROM tenants WHERE tenant_name IN ('ng', 'test-ng')")
    ).fetchall()

    for tenant in ng_tenants:
        tenant_id = tenant[0]

        # Check if the work type exists
        existing_work_type = conn.execute(
            text(
                """
                SELECT id FROM work_types
                WHERE tenant_id = :tenant_id
                AND name = 'Electric Distribution'
                AND archived_at IS NULL
            """
            ),
            {"tenant_id": tenant_id},
        ).fetchone()

        if not existing_work_type:
            # Get the core work type ID for 'General'
            general_core_work_type = conn.execute(
                text(
                    """
                    SELECT id FROM work_types
                    WHERE name = 'General'
                    AND tenant_id IS NULL
                    AND archived_at IS NULL
                """
                )
            ).fetchone()

            if general_core_work_type:
                # Create the tenant work type
                new_work_type_id = uuid.uuid4()
                conn.execute(
                    text(
                        """
                        INSERT INTO work_types (
                            id, name, tenant_id, core_work_type_ids, code
                        ) VALUES (
                            :id, 'Electric Distribution', :tenant_id, :core_work_type_ids, 'NG-JSB-GENERIC'
                        )
                    """
                    ),
                    {
                        "id": new_work_type_id,
                        "tenant_id": tenant_id,
                        "core_work_type_ids": [general_core_work_type[0]],
                    },
                )
        else:
            # Update existing work type's code
            conn.execute(
                text(
                    """
                    UPDATE work_types
                    SET code = 'NG-JSB-GENERIC'
                    WHERE id = :work_type_id
                """
                ),
                {"work_type_id": existing_work_type[0]},
            )

    # Handle natgrid tenant - set work type code to null
    natgrid_tenant = conn.execute(
        text("SELECT id FROM tenants WHERE tenant_name = 'natgrid'")
    ).fetchone()

    if natgrid_tenant:
        tenant_id = natgrid_tenant[0]

        # Find the work type for natgrid tenant
        natgrid_work_type = conn.execute(
            text(
                """
                SELECT id FROM work_types
                WHERE tenant_id = :tenant_id
                AND name = 'Electric Distribution'
                AND archived_at IS NULL
            """
            ),
            {"tenant_id": tenant_id},
        ).fetchone()

        if natgrid_work_type:
            # Update the work type code to null
            conn.execute(
                text(
                    """
                    UPDATE work_types
                    SET code = NULL
                    WHERE id = :work_type_id
                """
                ),
                {"work_type_id": natgrid_work_type[0]},
            )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
