"""add indexes for notifications

Revision ID: 9de57db0c808
Revises: 5105077d9975
Create Date: 2024-10-10 17:22:47.074297

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "9de57db0c808"
down_revision = "5105077d9975"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "notifications_user_details_device_id_key",
        "notifications_user_details",
        ["device_id"],
    )
    op.create_index(
        "notifications_user_details_updated_at_idx",
        "notifications_user_details",
        ["updated_at"],
        unique=False,
    )
    op.create_index(
        "notifications_created_at_idx", "notifications", ["created_at"], unique=False
    )
    op.create_index(
        "notifications_receiver_id_idx", "notifications", ["receiver_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("notifications_receiver_id_idx", table_name="notifications")
    op.drop_index("notifications_created_at_idx", table_name="notifications")
    op.drop_index(
        "notifications_user_details_updated_at_idx",
        table_name="notifications_user_details",
    )
    op.drop_constraint(
        "notifications_user_details_device_id_key",
        "notifications_user_details",
        type_="unique",
    )
    # ### end Alembic commands ###
