"""add opco full name column

Revision ID: a0ed35f7da8e
Revises: 95b2a2c82d88
Create Date: 2024-02-26 12:30:34.998376

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a0ed35f7da8e"
down_revision = "95b2a2c82d88"
branch_labels = None
depends_on = None


opco_name_mapping = {
    "BGE": "Baltimore Gas & Electric Co",
    "ComEd": "ComEd",
    "Corporate": "Exelon Business Servcs Co, LLC",
    "PECO": "PECO Energy Company",
    "PHI": "PHI Service Company",
    "ACE": "Atlantic City Electric Co",
    "DPL": "Delmarva Power & Light Co",
    "PEP": "Potomac Electric Power Co",
}


def upgrade():
    connection = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("opcos", sa.Column("full_name", sa.String(), nullable=True))
    for opco in opco_name_mapping:
        connection.execute(
            sa.text("UPDATE public.opcos set full_name=:fullname where name=:opco"),
            {"opco": opco, "fullname": opco_name_mapping[opco]},
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("opcos", "full_name")
    # ### end Alembic commands ###
