"""updated work_type name constraint

Revision ID: b50ab610b5e4
Revises: d08d4d877ff8
Create Date: 2024-06-03 19:10:11.691597

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "b50ab610b5e4"
down_revision = "d08d4d877ff8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("work_types_name_key", "work_types", type_="unique")
    op.create_unique_constraint(
        "work_types_tenant_id_name_key", "work_types", ["name", "tenant_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("work_types_tenant_id_name_key", "work_types", type_="unique")
    op.create_unique_constraint("work_types_name_key", "work_types", ["name"])
    # ### end Alembic commands ###
