"""Added work_types to natgrid jsb

Revision ID: c02d231568ca
Revises: a3ee7f1cadbb
Create Date: 2025-05-11 18:46:42.678579

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "c02d231568ca"
down_revision = "a3ee7f1cadbb"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "natgrid_jsbs",
        sa.Column("work_type_id", sqlmodel.sql.sqltypes.GUID(), nullable=True),
    )
    op.create_foreign_key(
        "fk_natgrid_jsbs_work_type_id",  # A name for the foreign key constraint (recommended)
        "natgrid_jsbs",  # The source table name
        "work_types",  # The referenced table name
        ["work_type_id"],  # The local column(s) in the source table
        ["id"],  # The remote column(s) in the referenced table
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_natgrid_jsbs_work_type_id", "natgrid_jsbs", type_="foreignkey"
    )
    op.drop_column("natgrid_jsbs", "work_type_id")
    # ### end Alembic commands ###
