"""add image_url column in library hazards table

Revision ID: ccc5f4318ed8
Revises: 3f5c709d7117
Create Date: 2023-10-10 15:41:19.861153

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ccc5f4318ed8"
down_revision = "3f5c709d7117"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "library_hazards",
        sa.Column(
            "image_url",
            sa.String(),
            server_default="https://restore-build-artefacts.s3.amazonaws.com/default_image.svg",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("library_hazards", "image_url")
    # ### end Alembic commands ###
