"""added lanid and company_name columns in crew_leader

Revision ID: cfcc3547aa59
Revises: d8ab0fc7aee1
Create Date: 2023-11-29 16:47:35.035288

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "cfcc3547aa59"
down_revision = "d8ab0fc7aee1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("crew_leader", sa.Column("lanid", sa.String(), nullable=True))
    op.add_column("crew_leader", sa.Column("company_name", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("crew_leader", "company_name")
    op.drop_column("crew_leader", "lanid")
    # ### end Alembic commands ###
