"""added core_work_type_ids and tenant_id in work_type

Revision ID: d08d4d877ff8
Revises: 03f5f41be158
Create Date: 2024-05-13 10:54:51.281600

"""

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "d08d4d877ff8"
down_revision = "03f5f41be158"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "work_type_library_site_condition_link",
        sa.Column("work_type_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column(
            "library_site_condition_id", sqlmodel.sql.sqltypes.GUID(), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["library_site_condition_id"],
            ["library_site_conditions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["work_type_id"],
            ["work_types.id"],
        ),
        sa.PrimaryKeyConstraint("work_type_id", "library_site_condition_id"),
    )
    op.create_index(
        "work_type_id_library_site_condition_id_idx",
        "work_type_library_site_condition_link",
        ["library_site_condition_id", "work_type_id"],
        unique=False,
    )
    op.add_column(
        "work_types",
        sa.Column(
            "core_work_type_ids", sa.ARRAY(postgresql.UUID(as_uuid=True)), nullable=True
        ),
    )
    op.add_column(
        "work_types",
        sa.Column("tenant_id", sqlmodel.sql.sqltypes.GUID(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("work_types", "tenant_id")
    op.drop_column("work_types", "core_work_type_ids")
    op.drop_index(
        "work_type_id_library_site_condition_id_idx",
        table_name="work_type_library_site_condition_link",
    )
    op.drop_table("work_type_library_site_condition_link")
    # ### end Alembic commands ###
