"""archived at field added for incidents

Revision ID: d0c3f1002352
Revises: eb9a950d1437
Create Date: 2023-11-28 12:13:31.787059

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d0c3f1002352"
down_revision = "0adeec5df6aa"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "incidents", sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("incidents", "archived_at")
    # ### end Alembic commands ###
