"""update existing ebo content to update label name from observations to hazards

Revision ID: d7bef659e68f
Revises: d5769b9ff60d
Create Date: 2024-03-05 11:16:07.381878

"""
import json

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d7bef659e68f"
down_revision = "d5769b9ff60d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()
    query = """
    SELECT id,contents
    FROM public.energy_based_observations;
    """

    sql = sa.text(query)
    rows = connection.execute(sql)

    for row in rows:
        high_energy_tasks = row.contents.get("high_energy_tasks")
        if high_energy_tasks:
            for task in high_energy_tasks:
                hazard = task["observations"]
                task["hazards"] = hazard
                del task["observations"]
            row.contents["high_energy_tasks"] = high_energy_tasks
        contents = json.dumps(row.contents)
        connection.execute(
            sa.text(
                "UPDATE public.energy_based_observations SET contents=:contents where id=:id"
            ),
            {"id": row.id, "contents": contents},
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()
    query = """
    SELECT id,contents
    FROM public.energy_based_observations;
    """

    sql = sa.text(query)
    rows = connection.execute(sql)

    for row in rows:
        high_energy_tasks = row.contents.get("high_energy_tasks")
        if high_energy_tasks:
            for task in high_energy_tasks:
                hazard = task["hazards"]
                task["observations"] = hazard
                del task["hazards"]
            row.contents["high_energy_tasks"] = high_energy_tasks
        contents = json.dumps(row.contents)
        connection.execute(
            sa.text(
                "UPDATE public.energy_based_observations SET contents=:contents where id=:id"
            ),
            {"id": row.id, "contents": contents},
        )
    # ### end Alembic commands ###
