"""added_date_range_indices_project_entities

Revision ID: e237ff10ad53
Revises: 0dc9ea45ab78
Create Date: 2024-07-26 18:20:55.302530

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e237ff10ad53"
down_revision = "0dc9ea45ab78"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_index(
        "work_packages_start_date_end_date_ix",
        "projects",
        [sa.text("start_date DESC"), sa.text("end_date DESC")],
    )
    op.create_index(
        "site_conditions_date_ix", "site_conditions", [sa.text("date DESC")]
    )
    op.create_index(
        "activities_start_date_end_date_ix",
        "activities",
        [sa.text("start_date DESC"), sa.text("end_date DESC")],
    )
    op.create_index(
        "tasks_start_date_end_date_ix",
        "tasks",
        [sa.text("start_date DESC"), sa.text("end_date DESC")],
    )
    op.create_index("jsbs_date_for_ix", "jsbs", [sa.text("date_for DESC")])
    op.create_index(
        "daily_reports_date_for_ix", "daily_reports", [sa.text("date_for DESC")]
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("work_packages_start_date_end_date_ix", table_name="projects")
    op.drop_index("site_conditions_date_ix", table_name="site_conditions")
    op.drop_index("activities_start_date_end_date_ix", table_name="activities")
    op.drop_index("tasks_start_date_end_date_ix", table_name="tasks")
    op.drop_index("jsbs_date_for_ix", table_name="jsbs")
    op.drop_index("daily_reports_date_for_ix", table_name="daily_reports")

    # ### end Alembic commands ###
