"""Update work_type id for older ngjsbs

Revision ID: e90acc206b7f
Revises: d4f840f96ba7
Create Date: 2025-06-02 14:23:34.539492

"""
from alembic import op
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision = "e90acc206b7f"
down_revision = "d4f840f96ba7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()

    # Get ng and test-ng tenants
    ng_tenants = conn.execute(
        text("SELECT id FROM tenants WHERE tenant_name IN ('ng', 'test-ng')")
    ).fetchall()

    for tenant in ng_tenants:
        tenant_id = tenant[0]

        # Find the work type for this tenant
        work_type = conn.execute(
            text(
                """
                SELECT id
                FROM work_types
                WHERE tenant_id = :tenant_id
                AND name = 'Electric Distribution'
                AND code = 'NG-JSB-GENERIC'
                AND archived_at IS NULL
                ORDER BY id
                LIMIT 1
            """
            ),
            {"tenant_id": tenant_id},
        ).fetchone()

        if work_type:
            work_type_id = work_type[0]

            # Update all natgrid_jsbs records for this tenant
            conn.execute(
                text(
                    """
                    UPDATE natgrid_jsbs
                    SET work_type_id = :work_type_id
                    WHERE tenant_id = :tenant_id
                """
                ),
                {
                    "work_type_id": work_type_id,
                    "tenant_id": tenant_id,
                },
            )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
