import type { FeaturesMap, TenantsList, Features } from "../useTenantFeatures";

// Only contains overrides from the default behavior
export const staging: FeaturesMap = new Map<TenantsList, Features>([
  [
    "urbint",
    {
      // Integration and Staging tenants
      displayJSB: true,
      displayFormsList: true,
      displayAddEbo: true,
      displayAddJsb: true,
      displayAddCriticalActivity: true,
      displayTemplatesList: true,
      displayTemplateFormsList: true,
    },
  ],
  [
    "georgia-power",
    {
      displayLearnings: false,
      displayInspections: false,
      displayProjectsAsLandingPage: false,
      displayTemplateFormsAsLandingPage: true,
      displayJSB: false,
      displayFormsList: false,
      displayAddEbo: false,
      displayAddJsb: false,
      displayProjectTaskRiskHeatmap: false,
      displayFormsAsLandingPage: false,
      displayPlannings: false,
      displayTemplatesList: true,
      displayTemplateFormsList: true,
    },
  ],
  [
    "exelon",
    {
      displayLearnings: false,
      displayInspections: false,
      displayProjectsAsLandingPage: false,
      displayFormsAsLandingPage: true,
      displayFormsList: true,
      displayAddEbo: true,
      displayWorkPackage: false,
      displayMap: false,
      displayPlannings: false,
    },
  ],
  [
    "xcelenergy",
    {
      displayLearnings: false,
      displayInspections: false,
      displayProjectsAsLandingPage: false,
      displayFormsAsLandingPage: true,
      displayFormsList: true,
      displayAddEbo: true,
      displayWorkPackage: false,
      displayMap: false,
      displayPlannings: false,
    },
  ],
  [
    "test-xcelenergy",
    {
      displayLearnings: false,
      displayInspections: false,
      displayProjectsAsLandingPage: false,
      displayFormsAsLandingPage: true,
      displayFormsList: true,
      displayAddEbo: true,
      displayWorkPackage: false,
      displayMap: false,
      displayPlannings: false,
    },
  ],
  [
    "natgrid",
    {
      displayAddEbo: false,
      displayFormsList: true,
      displayAddForm: false,
      displayAddCriticalActivity: true,
      displayProjectTaskRiskHeatmap: false,
      displayTemplatesList: true,
      displayTemplateFormsList: true,
    },
  ],
  [
    "test-ng",
    {
      displayLearnings: false,
      displayInspections: false,
      displayProjectsAsLandingPage: false,
      displayFormsAsLandingPage: true,
      displayFormsList: true,
      displayAddForm: false,
      displayAddEbo: false,
      displayAddJsb: false,
      displayWorkPackage: false,
      displayMap: false,
      displayPlannings: false,
    },
  ],
  [
    "ng",
    {
      displayLearnings: false,
      displayInspections: false,
      displayProjectsAsLandingPage: false,
      displayFormsAsLandingPage: true,
      displayFormsList: true,
      displayAddForm: false,
      displayAddEbo: false,
      displayAddJsb: false,
      displayWorkPackage: false,
      displayMap: false,
      displayPlannings: false,
    },
  ],
  [
    "ws-demo",
    {
      displayTemplatesList: true,
      displayTemplateFormsList: true,
    },
  ],
  [
    "dominion",
    {
      displayFormsList: false,
      displayAddForm: true,
      displayAddEbo: false,
      displayWorkPackage: true,
      displayProjectsAsLandingPage: true,
      displayMap: true,
      displayTemplatesList: true,
      displayTemplateFormsList: true,
      displayInsights: true,
    },
  ],
]);
