query ControlsLibrary(
  $type: LibraryFilterType!
  $libraryHazardId: UUID
  $libraryTaskId: UUID
  $librarySiteConditionId: UUID
  $orderBy: [OrderBy!]
) {
  controlsLibrary(
    type: $type
    libraryHazardId: $libraryHazardId
    libraryTaskId: $libraryTaskId
    librarySiteConditionId: $librarySiteConditionId
    orderBy: $orderBy
  ) {
    id
    name
    isApplicable
  }
}
