query HazardsLibrary(
  $type: LibraryFilterType!
  $libraryTaskId: UUID
  $librarySiteConditionId: UUID
  $orderBy: [OrderBy!]
) {
  hazardsLibrary(
    type: $type
    libraryTaskId: $libraryTaskId
    librarySiteConditionId: $librarySiteConditionId
    orderBy: $orderBy
  ) {
    id
    name
    isApplicable
    energyLevel
    energyType
    imageUrl
    controls {
      id
      name
      isApplicable
      controlType
      ppe
      archivedAt
    }
  }
}
