query ingestOptions {
  ingestOptions {
    options {
      id
      name
      description
      columns {
        attribute
        name
        requiredOnIngest
        ignoreOnIngest
      }
    }
  }
}
