query WorkTypeLinkedActivityTasks(
  $orderBy: [LibraryTaskOrderBy!]
  $workTypeIds: [UUID!]!
) {
  tenantAndWorkTypeLinkedLibraryTasks(
    orderBy: $orderBy
    tenantWorkTypeIds: $workTypeIds
  ) {
    id
    name
    category
    activitiesGroups {
      id
      name
      aliases
    }
    isCritical
  }
}
