query WorkTypeLinkedLibraryTasks(
  $tasksLibraryId: [UUID!]
  $orderBy: [LibraryTaskOrderBy!]
  $hazardsOrderBy: [OrderBy!]
  $controlsOrderBy: [OrderBy!]
  $workTypeIds: [UUID!]!
) {
  tenantAndWorkTypeLinkedLibraryTasks(
    ids: $tasksLibraryId
    tenantWorkTypeIds: $workTypeIds
    orderBy: $orderBy
  ) {
    id
    name
    riskLevel
    hespScore
    category
    isCritical
    workTypes {
      id
      name
    }
    hazards(orderBy: $hazardsOrderBy) {
      id
      name
      isApplicable
      controls(orderBy: $controlsOrderBy) {
        id
        name
        isApplicable
        ppe
      }
      energyType
      energyLevel
      imageUrl
      taskApplicabilityLevels {
        applicabilityLevel
        taskId
      }
      archivedAt
    }
    activitiesGroups {
      id
      name
      aliases
      tasks {
        id
      }
    }
  }
}
