mutation saveTemplateFormFilters($userId: UUID!, $data: String!) {
  saveUserPreferences(
    data: $data
    userId: $userId
    entityType: CWFTemplateFormFilters
  ) {
    id
    contents
    entityType
  }
}
